#ifndef _MSB1236C_H_
#define _MSB1236C_H_
#include <msAPI_Tuner.h>

#define INTERFACE extern
/*
typedef enum
{
	COFDM_FEC_LOCK,
	COFDM_PSYNC_LOCK,
	COFDM_TPS_LOCK,
	COFDM_DCR_LOCK,
	COFDM_AGC_LOCK,
	COFDM_MODE_DET,

} COFDM_LOCK_STATUS;
*//*
	typedef enum
	{
		E_DEVICE_DEMOD_ATV = 0,
		E_DEVICE_DEMOD_DVB_T,
		E_DEVICE_DEMOD_DVB_S,
		E_DEVICE_DEMOD_DTMB,
		E_DEVICE_DEMOD_ATSC,
		E_DEVICE_DEMOD_ATSC_VSB,
		E_DEVICE_DEMOD_ATSC_QPSK,
		E_DEVICE_DEMOD_ATSC_16QAM,
		E_DEVICE_DEMOD_ATSC_64QAM,
		E_DEVICE_DEMOD_ATSC_256QAM,
		E_DEVICE_DEMOD_DVB_T2,
		E_DEVICE_DEMOD_ISDB,
		E_DEVICE_DEMOD_MAX,
		E_DEVICE_DEMOD_NULL = E_DEVICE_DEMOD_MAX,
	} EN_DEVICE_DEMOD_TYPE;
*/
typedef enum
{
    COFDM_FEC_LOCK,
    COFDM_PSYNC_LOCK_123X,
    COFDM_TPS_LOCK,
    COFDM_TPS_LOCK_HISTORY_123X,
    COFDM_DCR_LOCK_123X,
    COFDM_AGC_LOCK_123X,
    COFDM_MODE_DET_123X,
    COFDM_LOCK_STABLE_DVBT_123X,
    COFDM_SYNC_LOCK_DVBT_123X,
    COFDM_FAST_LOCK_DVBT_123X,//add 0920
    //addy update 0805
    COFDM_P1_LOCK_123X,
    COFDM_P1_LOCK_HISTORY_123X,
    COFDM_L1_CRC_LOCK_123X,
} COFDM_LOCK_STATUS;
INTERFACE void MApi_FE_Power_On_Initialization(void);
INTERFACE void MApi_FE_SetFrequency(MS_U32 u32Frequency, MS_U8 eBandWidth);
INTERFACE MS_BOOL  MApi_FE_CheckLock(void);
INTERFACE MS_U32 MApi_FE_GetSNR(void);
INTERFACE MS_U16 MApi_FE_GetSignalQuality(void);




#undef INTERFACE
#endif

