# ****************************************
# chaltests makefile
# ****************************************
include $(BUILD_MAKE)/environnement.mak
include $(BUILD_EXE)/drivers.mak

# ****************************************
# Define module name
# ****************************************
MODULE  = pvrtests

# ****************************************
# This define the default command for gmake
# ****************************************
all: $(LIB_PREFFIX)$(MODULE).$(LIB_SUFFIX)

# ****************************************
# Include paths needed to compile those files
# ****************************************
DIR_INCLUDE = 

# ***************************************************
# List of object files needed to create library
# ***************************************************
LIBOBJS = 	

# ****************************************
# List of dependencies
# ****************************************

# ****************************************
# Always include crules.mak
# ****************************************
include $(BUILD_MAKE)/crules.mak
