#----------------------------------------------------------------------
#
#           Conditional Access Makefile
#
#----------------------------------------------------------------------

# Production libaries

CAK_PROD_RELEASE_LIBS = libcak_icme.std_nocert.release.mipsisa32-elf-gcc-DG2.a \
                        libcak_icme.std_nocert.release.mipsisa32-elf-gcc.a

CAK_PROD_DEBUG_LIBS   = libcak_icme.std_nocert.debug.mipsisa32-elf-gcc-DG2.a \
                        libcak_icme.std_nocert.debug.mipsisa32-elf-gcc.a

# Certification libaries
                        
CAK_NAK_RELEASE_LIBS =  libcak_icme.std_nocert.release.mipsisa32-elf-gcc-NAK.a \
                        libcak_icme.std_nocert.release.mipsisa32-elf-gcc.a

CAK_NAK_DEBUG_LIBS   =  libcak_icme.std_nocert.debug.mipsisa32-elf-gcc-NAK.a \
                        libcak_icme.std_nocert.debug.mipsisa32-elf-gcc.a
                        
# Driver Abstraction Layer Test Suite libraries

CAK_DALTS_LIBS        = libdalts.cak7-dlk-hybrid.release.mipsisa32-elf-gcc.a

CFLAGS += -D_NV_REMAP_DEFS_