#ifndef DALAPIVR_H
#define DALAPIVR_H
/* Generated by buildRevFileP4.py */
/* Information extracted from ../.././components/dalapi/p4codeline.xml */
/* P4 Path : //CAK/components/dalapi/TAGS/DALAPI_7_17_0 */
/* Last version: DALAPI_7_17_0 */
#define DALAPI_RELEASE "7.17.0"
#define DALAPI_NAME "DALAPI"
#define DALAPI_VERSION 007017000
#define DALAPI_BRANCH 000000
#define DALAPI_CANDIDATE 000
#endif /* DALAPIVR_H */
