/*
 * Automatically generated C config: don't edit
 * SBoot version: 1.0.0
 */
#define AUTOCONF_TIMESTAMP "2016-07-14 08:45:02 CEST"

#define CONFIG_HAVE_DOT_CONFIG 1
#define ENABLE_HAVE_DOT_CONFIG 1
#define USE_HAVE_DOT_CONFIG(...) __VA_ARGS__
#define SKIP_HAVE_DOT_CONFIG(...)

/*
 * Platform Configuration
 */
#undef CONFIG_MSTAR_URANUS4
#define ENABLE_MSTAR_URANUS4 0
#define USE_MSTAR_URANUS4(...)
#define SKIP_MSTAR_URANUS4(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS
#define ENABLE_MSTAR_KRONUS 0
#define USE_MSTAR_KRONUS(...)
#define SKIP_MSTAR_KRONUS(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN
#define ENABLE_MSTAR_KAISERIN 0
#define USE_MSTAR_KAISERIN(...)
#define SKIP_MSTAR_KAISERIN(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER
#define ENABLE_MSTAR_KAISER 0
#define USE_MSTAR_KAISER(...)
#define SKIP_MSTAR_KAISER(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAPPA
#define ENABLE_MSTAR_KAPPA 0
#define USE_MSTAR_KAPPA(...)
#define SKIP_MSTAR_KAPPA(...) __VA_ARGS__
#define CONFIG_MSTAR_KELTIC 1
#define ENABLE_MSTAR_KELTIC 1
#define USE_MSTAR_KELTIC(...) __VA_ARGS__
#define SKIP_MSTAR_KELTIC(...)
#define CONFIG_MSTAR_CHIP_NAME "keltic"
#define ENABLE_MSTAR_CHIP_NAME 1
#define USE_MSTAR_CHIP_NAME(...) __VA_ARGS__
#define SKIP_MSTAR_CHIP_NAME(...)
#define CONFIG_MCU_MIPS32 1
#define ENABLE_MCU_MIPS32 1
#define USE_MCU_MIPS32(...) __VA_ARGS__
#define SKIP_MCU_MIPS32(...)
#undef CONFIG_MCU_ARM
#define ENABLE_MCU_ARM 0
#define USE_MCU_ARM(...)
#define SKIP_MCU_ARM(...) __VA_ARGS__
#undef CONFIG_CPU_984MHZ
#define ENABLE_CPU_984MHZ 0
#define USE_CPU_984MHZ(...)
#define SKIP_CPU_984MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_1008MHZ
#define ENABLE_CPU_1008MHZ 0
#define USE_CPU_1008MHZ(...)
#define SKIP_CPU_1008MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_900MHZ
#define ENABLE_CPU_900MHZ 0
#define USE_CPU_900MHZ(...)
#define SKIP_CPU_900MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_840MHZ
#define ENABLE_CPU_840MHZ 0
#define USE_CPU_840MHZ(...)
#define SKIP_CPU_840MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_792MHZ
#define ENABLE_CPU_792MHZ 0
#define USE_CPU_792MHZ(...)
#define SKIP_CPU_792MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_720MHZ
#define ENABLE_CPU_720MHZ 0
#define USE_CPU_720MHZ(...)
#define SKIP_CPU_720MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_696MHZ
#define ENABLE_CPU_696MHZ 0
#define USE_CPU_696MHZ(...)
#define SKIP_CPU_696MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_600MHZ
#define ENABLE_CPU_600MHZ 0
#define USE_CPU_600MHZ(...)
#define SKIP_CPU_600MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_552MHZ
#define ENABLE_CPU_552MHZ 0
#define USE_CPU_552MHZ(...)
#define SKIP_CPU_552MHZ(...) __VA_ARGS__
#define CONFIG_CPU_504MHZ 1
#define ENABLE_CPU_504MHZ 1
#define USE_CPU_504MHZ(...) __VA_ARGS__
#define SKIP_CPU_504MHZ(...)
#undef CONFIG_CPU_456MHZ
#define ENABLE_CPU_456MHZ 0
#define USE_CPU_456MHZ(...)
#define SKIP_CPU_456MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_432MHZ
#define ENABLE_CPU_432MHZ 0
#define USE_CPU_432MHZ(...)
#define SKIP_CPU_432MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_396MHZ
#define ENABLE_CPU_396MHZ 0
#define USE_CPU_396MHZ(...)
#define SKIP_CPU_396MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_348MHZ
#define ENABLE_CPU_348MHZ 0
#define USE_CPU_348MHZ(...)
#define SKIP_CPU_348MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_336MHZ
#define ENABLE_CPU_336MHZ 0
#define USE_CPU_336MHZ(...)
#define SKIP_CPU_336MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_324MHZ
#define ENABLE_CPU_324MHZ 0
#define USE_CPU_324MHZ(...)
#define SKIP_CPU_324MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_312MHZ
#define ENABLE_CPU_312MHZ 0
#define USE_CPU_312MHZ(...)
#define SKIP_CPU_312MHZ(...) __VA_ARGS__
#undef CONFIG_CPU_288MHZ
#define ENABLE_CPU_288MHZ 0
#define USE_CPU_288MHZ(...)
#define SKIP_CPU_288MHZ(...) __VA_ARGS__
#undef CONFIG_MSTAR_MANUAL
#define ENABLE_MSTAR_MANUAL 0
#define USE_MSTAR_MANUAL(...)
#define SKIP_MSTAR_MANUAL(...) __VA_ARGS__
#define CONFIG_MSTAR_OTHERS 0
#define ENABLE_MSTAR_OTHERS 1
#define USE_MSTAR_OTHERS(...) __VA_ARGS__
#define SKIP_MSTAR_OTHERS(...)
#undef CONFIG_KRONUS_U04
#define ENABLE_KRONUS_U04 0
#define USE_KRONUS_U04(...)
#define SKIP_KRONUS_U04(...) __VA_ARGS__
#undef CONFIG_KRONUS_U03
#define ENABLE_KRONUS_U03 0
#define USE_KRONUS_U03(...)
#define SKIP_KRONUS_U03(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_FPGA
#define ENABLE_MSTAR_TITANIA_BD_FPGA 0
#define USE_MSTAR_TITANIA_BD_FPGA(...)
#define SKIP_MSTAR_TITANIA_BD_FPGA(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098A_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST098A_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST098A_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST098A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098B_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST098B_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST098B_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST098B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098B_D01A
#define ENABLE_MSTAR_TITANIA_BD_MST098B_D01A 0
#define USE_MSTAR_TITANIA_BD_MST098B_D01A(...)
#define SKIP_MSTAR_TITANIA_BD_MST098B_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098B_D01B
#define ENABLE_MSTAR_TITANIA_BD_MST098B_D01B 0
#define USE_MSTAR_TITANIA_BD_MST098B_D01B(...)
#define SKIP_MSTAR_TITANIA_BD_MST098B_D01B(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098C_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST098C_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST098C_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST098C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098D_D01A_S
#define ENABLE_MSTAR_TITANIA_BD_MST098D_D01A_S 0
#define USE_MSTAR_TITANIA_BD_MST098D_D01A_S(...)
#define SKIP_MSTAR_TITANIA_BD_MST098D_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098E_D01A
#define ENABLE_MSTAR_TITANIA_BD_MST098E_D01A 0
#define USE_MSTAR_TITANIA_BD_MST098E_D01A(...)
#define SKIP_MSTAR_TITANIA_BD_MST098E_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098E_D01B
#define ENABLE_MSTAR_TITANIA_BD_MST098E_D01B 0
#define USE_MSTAR_TITANIA_BD_MST098E_D01B(...)
#define SKIP_MSTAR_TITANIA_BD_MST098E_D01B(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098F_D01A
#define ENABLE_MSTAR_TITANIA_BD_MST098F_D01A 0
#define USE_MSTAR_TITANIA_BD_MST098F_D01A(...)
#define SKIP_MSTAR_TITANIA_BD_MST098F_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST098F_D01B
#define ENABLE_MSTAR_TITANIA_BD_MST098F_D01B 0
#define USE_MSTAR_TITANIA_BD_MST098F_D01B(...)
#define SKIP_MSTAR_TITANIA_BD_MST098F_D01B(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_MST128A_D01A
#define ENABLE_MSTAR_TITANIA_BD_MST128A_D01A 0
#define USE_MSTAR_TITANIA_BD_MST128A_D01A(...)
#define SKIP_MSTAR_TITANIA_BD_MST128A_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_ZDT300_V01
#define ENABLE_MSTAR_TITANIA_BD_ZDT300_V01 0
#define USE_MSTAR_TITANIA_BD_ZDT300_V01(...)
#define SKIP_MSTAR_TITANIA_BD_ZDT300_V01(...) __VA_ARGS__
#undef CONFIG_MSTAR_TITANIA_BD_CUS75_MBQ213A
#define ENABLE_MSTAR_TITANIA_BD_CUS75_MBQ213A 0
#define USE_MSTAR_TITANIA_BD_CUS75_MBQ213A(...)
#define SKIP_MSTAR_TITANIA_BD_CUS75_MBQ213A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124A_D01A
#define ENABLE_MSTAR_KRONUS_BD_MST124A_D01A 0
#define USE_MSTAR_KRONUS_BD_MST124A_D01A(...)
#define SKIP_MSTAR_KRONUS_BD_MST124A_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124A_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124A_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST124A_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124A_D02A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124A_D02A_S 0
#define USE_MSTAR_KRONUS_BD_MST124A_D02A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124A_D02A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124B_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124B_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST124B_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124B_D02A
#define ENABLE_MSTAR_KRONUS_BD_MST124B_D02A 0
#define USE_MSTAR_KRONUS_BD_MST124B_D02A(...)
#define SKIP_MSTAR_KRONUS_BD_MST124B_D02A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124B_D02A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124B_D02A_S 0
#define USE_MSTAR_KRONUS_BD_MST124B_D02A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124B_D02A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124C_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124C_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST124C_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124C_D02A
#define ENABLE_MSTAR_KRONUS_BD_MST124C_D02A 0
#define USE_MSTAR_KRONUS_BD_MST124C_D02A(...)
#define SKIP_MSTAR_KRONUS_BD_MST124C_D02A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124D_D01A
#define ENABLE_MSTAR_KRONUS_BD_MST124D_D01A 0
#define USE_MSTAR_KRONUS_BD_MST124D_D01A(...)
#define SKIP_MSTAR_KRONUS_BD_MST124D_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124D_D02A
#define ENABLE_MSTAR_KRONUS_BD_MST124D_D02A 0
#define USE_MSTAR_KRONUS_BD_MST124D_D02A(...)
#define SKIP_MSTAR_KRONUS_BD_MST124D_D02A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124D_D02A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124D_D02A_S 0
#define USE_MSTAR_KRONUS_BD_MST124D_D02A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124D_D02A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124E_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124E_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST124E_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124E_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124E_D01A_SZ
#define ENABLE_MSTAR_KRONUS_BD_MST124E_D01A_SZ 0
#define USE_MSTAR_KRONUS_BD_MST124E_D01A_SZ(...)
#define SKIP_MSTAR_KRONUS_BD_MST124E_D01A_SZ(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124SZ
#define ENABLE_MSTAR_KRONUS_BD_MST124SZ 0
#define USE_MSTAR_KRONUS_BD_MST124SZ(...)
#define SKIP_MSTAR_KRONUS_BD_MST124SZ(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124G_D01A
#define ENABLE_MSTAR_KRONUS_BD_MST124G_D01A 0
#define USE_MSTAR_KRONUS_BD_MST124G_D01A(...)
#define SKIP_MSTAR_KRONUS_BD_MST124G_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124G_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124G_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST124G_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124G_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST140A_D01A
#define ENABLE_MSTAR_KRONUS_BD_MST140A_D01A 0
#define USE_MSTAR_KRONUS_BD_MST140A_D01A(...)
#define SKIP_MSTAR_KRONUS_BD_MST140A_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST140A_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST140A_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST140A_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST140A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST163A_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST163A_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST163A_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST163A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124F_D01A_S
#define ENABLE_MSTAR_KRONUS_BD_MST124F_D01A_S 0
#define USE_MSTAR_KRONUS_BD_MST124F_D01A_S(...)
#define SKIP_MSTAR_KRONUS_BD_MST124F_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124F_SZ_Demo
#define ENABLE_MSTAR_KRONUS_BD_MST124F_SZ_Demo 0
#define USE_MSTAR_KRONUS_BD_MST124F_SZ_Demo(...)
#define SKIP_MSTAR_KRONUS_BD_MST124F_SZ_Demo(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_MST124F_D02A
#define ENABLE_MSTAR_KRONUS_BD_MST124F_D02A 0
#define USE_MSTAR_KRONUS_BD_MST124F_D02A(...)
#define SKIP_MSTAR_KRONUS_BD_MST124F_D02A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KRONUS_BD_SS2000_DT0A
#define ENABLE_MSTAR_KRONUS_BD_SS2000_DT0A 0
#define USE_MSTAR_KRONUS_BD_SS2000_DT0A(...)
#define SKIP_MSTAR_KRONUS_BD_SS2000_DT0A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_BD_MST138A_D01A_S
#define ENABLE_MSTAR_KAISERIN_BD_MST138A_D01A_S 0
#define USE_MSTAR_KAISERIN_BD_MST138A_D01A_S(...)
#define SKIP_MSTAR_KAISERIN_BD_MST138A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_BD_MST138A_D01A
#define ENABLE_MSTAR_KAISERIN_BD_MST138A_D01A 0
#define USE_MSTAR_KAISERIN_BD_MST138A_D01A(...)
#define SKIP_MSTAR_KAISERIN_BD_MST138A_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_BD_MST138B_D01A_S
#define ENABLE_MSTAR_KAISERIN_BD_MST138B_D01A_S 0
#define USE_MSTAR_KAISERIN_BD_MST138B_D01A_S(...)
#define SKIP_MSTAR_KAISERIN_BD_MST138B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_BD_MST138B_D01A
#define ENABLE_MSTAR_KAISERIN_BD_MST138B_D01A 0
#define USE_MSTAR_KAISERIN_BD_MST138B_D01A(...)
#define SKIP_MSTAR_KAISERIN_BD_MST138B_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_BD_MST138B_D01D
#define ENABLE_MSTAR_KAISERIN_BD_MST138B_D01D 0
#define USE_MSTAR_KAISERIN_BD_MST138B_D01D(...)
#define SKIP_MSTAR_KAISERIN_BD_MST138B_D01D(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_BD_MST178A_D01A_S
#define ENABLE_MSTAR_KAISERIN_BD_MST178A_D01A_S 0
#define USE_MSTAR_KAISERIN_BD_MST178A_D01A_S(...)
#define SKIP_MSTAR_KAISERIN_BD_MST178A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISERIN_BD_MST178A_D01A
#define ENABLE_MSTAR_KAISERIN_BD_MST178A_D01A 0
#define USE_MSTAR_KAISERIN_BD_MST178A_D01A(...)
#define SKIP_MSTAR_KAISERIN_BD_MST178A_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER_BD_FPGA
#define ENABLE_MSTAR_KAISER_BD_FPGA 0
#define USE_MSTAR_KAISER_BD_FPGA(...)
#define SKIP_MSTAR_KAISER_BD_FPGA(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER_BD_MST170A_D01A_S
#define ENABLE_MSTAR_KAISER_BD_MST170A_D01A_S 0
#define USE_MSTAR_KAISER_BD_MST170A_D01A_S(...)
#define SKIP_MSTAR_KAISER_BD_MST170A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER_BD_MST170A_D01A
#define ENABLE_MSTAR_KAISER_BD_MST170A_D01A 0
#define USE_MSTAR_KAISER_BD_MST170A_D01A(...)
#define SKIP_MSTAR_KAISER_BD_MST170A_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER_BD_MST170A_D01A_SZ
#define ENABLE_MSTAR_KAISER_BD_MST170A_D01A_SZ 0
#define USE_MSTAR_KAISER_BD_MST170A_D01A_SZ(...)
#define SKIP_MSTAR_KAISER_BD_MST170A_D01A_SZ(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER_BD_MST170B_D01A_S
#define ENABLE_MSTAR_KAISER_BD_MST170B_D01A_S 0
#define USE_MSTAR_KAISER_BD_MST170B_D01A_S(...)
#define SKIP_MSTAR_KAISER_BD_MST170B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER_BD_MST170A_D02A
#define ENABLE_MSTAR_KAISER_BD_MST170A_D02A 0
#define USE_MSTAR_KAISER_BD_MST170A_D02A(...)
#define SKIP_MSTAR_KAISER_BD_MST170A_D02A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER_BD_D3C_L4D_V01
#define ENABLE_MSTAR_KAISER_BD_D3C_L4D_V01 0
#define USE_MSTAR_KAISER_BD_D3C_L4D_V01(...)
#define SKIP_MSTAR_KAISER_BD_D3C_L4D_V01(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER_BD_D3B_L2S_V01
#define ENABLE_MSTAR_KAISER_BD_D3B_L2S_V01 0
#define USE_MSTAR_KAISER_BD_D3B_L2S_V01(...)
#define SKIP_MSTAR_KAISER_BD_D3B_L2S_V01(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER_BD_MP3050_SR1
#define ENABLE_MSTAR_KAISER_BD_MP3050_SR1 0
#define USE_MSTAR_KAISER_BD_MP3050_SR1(...)
#define SKIP_MSTAR_KAISER_BD_MP3050_SR1(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER_BD_MP3050_SR2
#define ENABLE_MSTAR_KAISER_BD_MP3050_SR2 0
#define USE_MSTAR_KAISER_BD_MP3050_SR2(...)
#define SKIP_MSTAR_KAISER_BD_MP3050_SR2(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAISER_BD_MST187A_D01A
#define ENABLE_MSTAR_KAISER_BD_MST187A_D01A 0
#define USE_MSTAR_KAISER_BD_MST187A_D01A(...)
#define SKIP_MSTAR_KAISER_BD_MST187A_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAPPA_BD_FPGA
#define ENABLE_MSTAR_KAPPA_BD_FPGA 0
#define USE_MSTAR_KAPPA_BD_FPGA(...)
#define SKIP_MSTAR_KAPPA_BD_FPGA(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAPPA_BD_MST173A_D01A_S
#define ENABLE_MSTAR_KAPPA_BD_MST173A_D01A_S 0
#define USE_MSTAR_KAPPA_BD_MST173A_D01A_S(...)
#define SKIP_MSTAR_KAPPA_BD_MST173A_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAPPA_BD_MST173A_D01A
#define ENABLE_MSTAR_KAPPA_BD_MST173A_D01A 0
#define USE_MSTAR_KAPPA_BD_MST173A_D01A(...)
#define SKIP_MSTAR_KAPPA_BD_MST173A_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAPPA_BD_MST173B_D01A_S
#define ENABLE_MSTAR_KAPPA_BD_MST173B_D01A_S 0
#define USE_MSTAR_KAPPA_BD_MST173B_D01A_S(...)
#define SKIP_MSTAR_KAPPA_BD_MST173B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAPPA_BD_MST173B_D01A
#define ENABLE_MSTAR_KAPPA_BD_MST173B_D01A 0
#define USE_MSTAR_KAPPA_BD_MST173B_D01A(...)
#define SKIP_MSTAR_KAPPA_BD_MST173B_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAPPA_BD_MST173C_D01A_S
#define ENABLE_MSTAR_KAPPA_BD_MST173C_D01A_S 0
#define USE_MSTAR_KAPPA_BD_MST173C_D01A_S(...)
#define SKIP_MSTAR_KAPPA_BD_MST173C_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KAPPA_BD_MST173C_D01A
#define ENABLE_MSTAR_KAPPA_BD_MST173C_D01A 0
#define USE_MSTAR_KAPPA_BD_MST173C_D01A(...)
#define SKIP_MSTAR_KAPPA_BD_MST173C_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KELTIC_FPGA
#define ENABLE_MSTAR_KELTIC_FPGA 0
#define USE_MSTAR_KELTIC_FPGA(...)
#define SKIP_MSTAR_KELTIC_FPGA(...) __VA_ARGS__
#define CONFIG_MSTAR_KELTIC_BD_MST183A_D01A_S 1
#define ENABLE_MSTAR_KELTIC_BD_MST183A_D01A_S 1
#define USE_MSTAR_KELTIC_BD_MST183A_D01A_S(...) __VA_ARGS__
#define SKIP_MSTAR_KELTIC_BD_MST183A_D01A_S(...)
#undef CONFIG_MSTAR_KELTIC_BD_MST183A_D01A
#define ENABLE_MSTAR_KELTIC_BD_MST183A_D01A 0
#define USE_MSTAR_KELTIC_BD_MST183A_D01A(...)
#define SKIP_MSTAR_KELTIC_BD_MST183A_D01A(...) __VA_ARGS__
#undef CONFIG_MSTAR_KELTIC_BD_MST183B_D01A_S
#define ENABLE_MSTAR_KELTIC_BD_MST183B_D01A_S 0
#define USE_MSTAR_KELTIC_BD_MST183B_D01A_S(...)
#define SKIP_MSTAR_KELTIC_BD_MST183B_D01A_S(...) __VA_ARGS__
#undef CONFIG_MSTAR_KELTIC_BD_MST183B_D01A
#define ENABLE_MSTAR_KELTIC_BD_MST183B_D01A 0
#define USE_MSTAR_KELTIC_BD_MST183B_D01A(...)
#define SKIP_MSTAR_KELTIC_BD_MST183B_D01A(...) __VA_ARGS__
#define CONFIG_MSD5XX5 1
#define ENABLE_MSD5XX5 1
#define USE_MSD5XX5(...) __VA_ARGS__
#define SKIP_MSD5XX5(...)
#undef CONFIG_MSD5XX3
#define ENABLE_MSD5XX3 0
#define USE_MSD5XX3(...)
#define SKIP_MSD5XX3(...) __VA_ARGS__
#undef CONFIG_MSD5XX1
#define ENABLE_MSD5XX1 0
#define USE_MSD5XX1(...)
#define SKIP_MSD5XX1(...) __VA_ARGS__
#undef CONFIG_MSD5XX7
#define ENABLE_MSD5XX7 0
#define USE_MSD5XX7(...)
#define SKIP_MSD5XX7(...) __VA_ARGS__
#undef CONFIG_MSD5XX9
#define ENABLE_MSD5XX9 0
#define USE_MSD5XX9(...)
#define SKIP_MSD5XX9(...) __VA_ARGS__
#undef CONFIG_DDR2_INTERFACE_FPGA
#define ENABLE_DDR2_INTERFACE_FPGA 0
#define USE_DDR2_INTERFACE_FPGA(...)
#define SKIP_DDR2_INTERFACE_FPGA(...) __VA_ARGS__
#undef CONFIG_DDR2_INTERFACE_QFP_128
#define ENABLE_DDR2_INTERFACE_QFP_128 0
#define USE_DDR2_INTERFACE_QFP_128(...)
#define SKIP_DDR2_INTERFACE_QFP_128(...) __VA_ARGS__
#undef CONFIG_DDR2_INTERFACE_QFP_128_V2
#define ENABLE_DDR2_INTERFACE_QFP_128_V2 0
#define USE_DDR2_INTERFACE_QFP_128_V2(...)
#define SKIP_DDR2_INTERFACE_QFP_128_V2(...) __VA_ARGS__
#undef CONFIG_DDR3_INTERFACE_QFP_156
#define ENABLE_DDR3_INTERFACE_QFP_156 0
#define USE_DDR3_INTERFACE_QFP_156(...)
#define SKIP_DDR3_INTERFACE_QFP_156(...) __VA_ARGS__
#undef CONFIG_DDR3_INTERFACE_QFP_128
#define ENABLE_DDR3_INTERFACE_QFP_128 0
#define USE_DDR3_INTERFACE_QFP_128(...)
#define SKIP_DDR3_INTERFACE_QFP_128(...) __VA_ARGS__
#undef CONFIG_PANEL_RES_FULL_HD
#define ENABLE_PANEL_RES_FULL_HD 0
#define USE_PANEL_RES_FULL_HD(...)
#define SKIP_PANEL_RES_FULL_HD(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_720P_50
#define ENABLE_PNL_DACOUT_720P_50 0
#define USE_PNL_DACOUT_720P_50(...)
#define SKIP_PNL_DACOUT_720P_50(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080I_50
#define ENABLE_PNL_DACOUT_1080I_50 0
#define USE_PNL_DACOUT_1080I_50(...)
#define SKIP_PNL_DACOUT_1080I_50(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080P_50
#define ENABLE_PNL_DACOUT_1080P_50 0
#define USE_PNL_DACOUT_1080P_50(...)
#define SKIP_PNL_DACOUT_1080P_50(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_480I
#define ENABLE_PNL_DACOUT_480I 0
#define USE_PNL_DACOUT_480I(...)
#define SKIP_PNL_DACOUT_480I(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_480P
#define ENABLE_PNL_DACOUT_480P 0
#define USE_PNL_DACOUT_480P(...)
#define SKIP_PNL_DACOUT_480P(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_720P_60
#define ENABLE_PNL_DACOUT_720P_60 0
#define USE_PNL_DACOUT_720P_60(...)
#define SKIP_PNL_DACOUT_720P_60(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080I_60
#define ENABLE_PNL_DACOUT_1080I_60 0
#define USE_PNL_DACOUT_1080I_60(...)
#define SKIP_PNL_DACOUT_1080I_60(...) __VA_ARGS__
#undef CONFIG_PNL_DACOUT_1080P_60
#define ENABLE_PNL_DACOUT_1080P_60 0
#define USE_PNL_DACOUT_1080P_60(...)
#define SKIP_PNL_DACOUT_1080P_60(...) __VA_ARGS__
#define CONFIG_PNL_DACOUT_576I 1
#define ENABLE_PNL_DACOUT_576I 1
#define USE_PNL_DACOUT_576I(...) __VA_ARGS__
#define SKIP_PNL_DACOUT_576I(...)
#undef CONFIG_PNL_DACOUT_576P
#define ENABLE_PNL_DACOUT_576P 0
#define USE_PNL_DACOUT_576P(...)
#define SKIP_PNL_DACOUT_576P(...) __VA_ARGS__
#undef CONFIG_MSTAR_MMAP_512MB_512MB
#define ENABLE_MSTAR_MMAP_512MB_512MB 0
#define USE_MSTAR_MMAP_512MB_512MB(...)
#define SKIP_MSTAR_MMAP_512MB_512MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MMAP_256MB_256MB
#define ENABLE_MSTAR_MMAP_256MB_256MB 0
#define USE_MSTAR_MMAP_256MB_256MB(...)
#define SKIP_MSTAR_MMAP_256MB_256MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MMAP_128MB_128MB
#define ENABLE_MSTAR_MMAP_128MB_128MB 0
#define USE_MSTAR_MMAP_128MB_128MB(...)
#define SKIP_MSTAR_MMAP_128MB_128MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MMAP_128MB_64MB
#define ENABLE_MSTAR_MMAP_128MB_64MB 0
#define USE_MSTAR_MMAP_128MB_64MB(...)
#define SKIP_MSTAR_MMAP_128MB_64MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MMAP_64MB_64MB
#define ENABLE_MSTAR_MMAP_64MB_64MB 0
#define USE_MSTAR_MMAP_64MB_64MB(...)
#define SKIP_MSTAR_MMAP_64MB_64MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MMAP_64MB_32MB
#define ENABLE_MSTAR_MMAP_64MB_32MB 0
#define USE_MSTAR_MMAP_64MB_32MB(...)
#define SKIP_MSTAR_MMAP_64MB_32MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MMAP_32MB_32MB
#define ENABLE_MSTAR_MMAP_32MB_32MB 0
#define USE_MSTAR_MMAP_32MB_32MB(...)
#define SKIP_MSTAR_MMAP_32MB_32MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MMAP_512MB
#define ENABLE_MSTAR_MMAP_512MB 0
#define USE_MSTAR_MMAP_512MB(...)
#define SKIP_MSTAR_MMAP_512MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MMAP_256MB
#define ENABLE_MSTAR_MMAP_256MB 0
#define USE_MSTAR_MMAP_256MB(...)
#define SKIP_MSTAR_MMAP_256MB(...) __VA_ARGS__
#undef CONFIG_MSTAR_MMAP_128MB
#define ENABLE_MSTAR_MMAP_128MB 0
#define USE_MSTAR_MMAP_128MB(...)
#define SKIP_MSTAR_MMAP_128MB(...) __VA_ARGS__
#define CONFIG_MSTAR_MMAP_64MB 1
#define ENABLE_MSTAR_MMAP_64MB 1
#define USE_MSTAR_MMAP_64MB(...) __VA_ARGS__
#define SKIP_MSTAR_MMAP_64MB(...)
#undef CONFIG_MSTAR_MMAP_32MB
#define ENABLE_MSTAR_MMAP_32MB 0
#define USE_MSTAR_MMAP_32MB(...)
#define SKIP_MSTAR_MMAP_32MB(...) __VA_ARGS__
#define CONFIG_MEM800MHz 1
#define ENABLE_MEM800MHz 1
#define USE_MEM800MHz(...) __VA_ARGS__
#define SKIP_MEM800MHz(...)
#undef CONFIG_MEM667MHz
#define ENABLE_MEM667MHz 0
#define USE_MEM667MHz(...)
#define SKIP_MEM667MHz(...) __VA_ARGS__
#undef CONFIG_MEM1333MHz
#define ENABLE_MEM1333MHz 0
#define USE_MEM1333MHz(...)
#define SKIP_MEM1333MHz(...) __VA_ARGS__
#undef CONFIG_UNSUPPORT_MEM_CLOCK
#define ENABLE_UNSUPPORT_MEM_CLOCK 0
#define USE_UNSUPPORT_MEM_CLOCK(...)
#define SKIP_UNSUPPORT_MEM_CLOCK(...) __VA_ARGS__
#undef CONFIG_DRAM_MOBF
#define ENABLE_DRAM_MOBF 0
#define USE_DRAM_MOBF(...)
#define SKIP_DRAM_MOBF(...) __VA_ARGS__
#undef CONFIG_BOOTING_FROM_EXT_SPI_WITH_CPU
#define ENABLE_BOOTING_FROM_EXT_SPI_WITH_CPU 0
#define USE_BOOTING_FROM_EXT_SPI_WITH_CPU(...)
#define SKIP_BOOTING_FROM_EXT_SPI_WITH_CPU(...) __VA_ARGS__
#define CONFIG_MIU0_BUSADDR 0x
#define ENABLE_MIU0_BUSADDR 1
#define USE_MIU0_BUSADDR(...) __VA_ARGS__
#define SKIP_MIU0_BUSADDR(...)
#define CONFIG_MIU1_BUSADDR 0x
#define ENABLE_MIU1_BUSADDR 1
#define USE_MIU1_BUSADDR(...) __VA_ARGS__
#define SKIP_MIU1_BUSADDR(...)
#undef CONFIG_MBOOT_IN_SPI_FLASH
#define ENABLE_MBOOT_IN_SPI_FLASH 0
#define USE_MBOOT_IN_SPI_FLASH(...)
#define SKIP_MBOOT_IN_SPI_FLASH(...) __VA_ARGS__
#undef CONFIG_MBOOT_IN_NAND_FLASH
#define ENABLE_MBOOT_IN_NAND_FLASH 0
#define USE_MBOOT_IN_NAND_FLASH(...)
#define SKIP_MBOOT_IN_NAND_FLASH(...) __VA_ARGS__
#undef CONFIG_MBOOT_IN_MMC_FLASH
#define ENABLE_MBOOT_IN_MMC_FLASH 0
#define USE_MBOOT_IN_MMC_FLASH(...)
#define SKIP_MBOOT_IN_MMC_FLASH(...) __VA_ARGS__
#define CONFIG_BOOTRAM_LOADADDR 0x81000000
#define ENABLE_BOOTRAM_LOADADDR 1
#define USE_BOOTRAM_LOADADDR(...) __VA_ARGS__
#define SKIP_BOOTRAM_LOADADDR(...)
#define CONFIG_UBOOT_LOADADDR 0x
#define ENABLE_UBOOT_LOADADDR 1
#define USE_UBOOT_LOADADDR(...) __VA_ARGS__
#define SKIP_UBOOT_LOADADDR(...)
#define CONFIG_KERNEL_START_ADDRESS 0x
#define ENABLE_KERNEL_START_ADDRESS 1
#define USE_KERNEL_START_ADDRESS(...) __VA_ARGS__
#define SKIP_KERNEL_START_ADDRESS(...)
#define CONFIG_DRAM_SIZE_MB_RELOCATE 0
#define ENABLE_DRAM_SIZE_MB_RELOCATE 1
#define USE_DRAM_SIZE_MB_RELOCATE(...) __VA_ARGS__
#define SKIP_DRAM_SIZE_MB_RELOCATE(...)

/*
 * Extended CPU Configuration
 */
#undef CONFIG_MSTAR_L2_CACHE_ENABLE
#define ENABLE_MSTAR_L2_CACHE_ENABLE 0
#define USE_MSTAR_L2_CACHE_ENABLE(...)
#define SKIP_MSTAR_L2_CACHE_ENABLE(...) __VA_ARGS__
#define CONFIG_MSTAR_FPU_ENABLE 1
#define ENABLE_MSTAR_FPU_ENABLE 1
#define USE_MSTAR_FPU_ENABLE(...) __VA_ARGS__
#define SKIP_MSTAR_FPU_ENABLE(...)
#define CONFIG_MSTAR_DRAM_AUTO_PHASE_ENABLE 1
#define ENABLE_MSTAR_DRAM_AUTO_PHASE_ENABLE 1
#define USE_MSTAR_DRAM_AUTO_PHASE_ENABLE(...) __VA_ARGS__
#define SKIP_MSTAR_DRAM_AUTO_PHASE_ENABLE(...)

/*
 * General Configuration
 */
#undef CONFIG_UBOOT_AS_2ED_LOADER
#define ENABLE_UBOOT_AS_2ED_LOADER 0
#define USE_UBOOT_AS_2ED_LOADER(...)
#define SKIP_UBOOT_AS_2ED_LOADER(...) __VA_ARGS__
#define CONFIG_ECOS_AS_2ED_LOADER 1
#define ENABLE_ECOS_AS_2ED_LOADER 1
#define USE_ECOS_AS_2ED_LOADER(...) __VA_ARGS__
#define SKIP_ECOS_AS_2ED_LOADER(...)
#undef CONFIG_NO_2ED_LOADER
#define ENABLE_NO_2ED_LOADER 0
#define USE_NO_2ED_LOADER(...)
#define SKIP_NO_2ED_LOADER(...) __VA_ARGS__
#define CONFIG_ECOS_ELF_PATH "keltic_ecos.elf"
#define ENABLE_ECOS_ELF_PATH 1
#define USE_ECOS_ELF_PATH(...) __VA_ARGS__
#define SKIP_ECOS_ELF_PATH(...)
#define CONFIG_LD_GENERIC 1
#define ENABLE_LD_GENERIC 1
#define USE_LD_GENERIC(...) __VA_ARGS__
#define SKIP_LD_GENERIC(...)
#undef CONFIG_LD_BOOT_FROM_OTP
#define ENABLE_LD_BOOT_FROM_OTP 0
#define USE_LD_BOOT_FROM_OTP(...)
#define SKIP_LD_BOOT_FROM_OTP(...) __VA_ARGS__
#define CONFIG_LDR_LZMA_COMPRESS 1
#define ENABLE_LDR_LZMA_COMPRESS 1
#define USE_LDR_LZMA_COMPRESS(...) __VA_ARGS__
#define SKIP_LDR_LZMA_COMPRESS(...)
#undef CONFIG_LDR_MSCOMPRESS
#define ENABLE_LDR_MSCOMPRESS 0
#define USE_LDR_MSCOMPRESS(...)
#define SKIP_LDR_MSCOMPRESS(...) __VA_ARGS__
#undef CONFIG_MSTAR_MARIA10_PM
#define ENABLE_MSTAR_MARIA10_PM 0
#define USE_MSTAR_MARIA10_PM(...)
#define SKIP_MSTAR_MARIA10_PM(...) __VA_ARGS__
#define CONFIG_COMPRESSED_BUFFER 0x80830000
#define ENABLE_COMPRESSED_BUFFER 1
#define USE_COMPRESSED_BUFFER(...) __VA_ARGS__
#define SKIP_COMPRESSED_BUFFER(...)
#define CONFIG_COMPRESSED_BUFFER 0x80830000
#define ENABLE_COMPRESSED_BUFFER 1
#define USE_COMPRESSED_BUFFER(...) __VA_ARGS__
#define SKIP_COMPRESSED_BUFFER(...)
#define CONFIG_COMPRESSED_LENGTH 0x700000
#define ENABLE_COMPRESSED_LENGTH 1
#define USE_COMPRESSED_LENGTH(...) __VA_ARGS__
#define SKIP_COMPRESSED_LENGTH(...)
#define CONFIG_DECOMPRESS_POOL_ADDRESS 0x80810000
#define ENABLE_DECOMPRESS_POOL_ADDRESS 1
#define USE_DECOMPRESS_POOL_ADDRESS(...) __VA_ARGS__
#define SKIP_DECOMPRESS_POOL_ADDRESS(...)
#define CONFIG_DECOMPRESS_POOL_ADDRESS 0x80810000
#define ENABLE_DECOMPRESS_POOL_ADDRESS 1
#define USE_DECOMPRESS_POOL_ADDRESS(...) __VA_ARGS__
#define SKIP_DECOMPRESS_POOL_ADDRESS(...)
#define CONFIG_DECOMPRESS_POOL_LENGTH 0x20000
#define ENABLE_DECOMPRESS_POOL_LENGTH 1
#define USE_DECOMPRESS_POOL_LENGTH(...) __VA_ARGS__
#define SKIP_DECOMPRESS_POOL_LENGTH(...)

/*
 * Build Options
 */
#define CONFIG_CROSS_COMPILER_PREFIX "mips-linux-gnu-"
#define ENABLE_CROSS_COMPILER_PREFIX 1
#define USE_CROSS_COMPILER_PREFIX(...) __VA_ARGS__
#define SKIP_CROSS_COMPILER_PREFIX(...)
#define CONFIG_EXTRA_CFLAGS "-EL"
#define ENABLE_EXTRA_CFLAGS 1
#define USE_EXTRA_CFLAGS(...) __VA_ARGS__
#define SKIP_EXTRA_CFLAGS(...)
#define CONFIG_EXTRA_AFLAGS ""
#define ENABLE_EXTRA_AFLAGS 1
#define USE_EXTRA_AFLAGS(...) __VA_ARGS__
#define SKIP_EXTRA_AFLAGS(...)

/*
 * Debugging Options
 */
#undef CONFIG_DEBUG
#define ENABLE_DEBUG 0
#define USE_DEBUG(...)
#define SKIP_DEBUG(...) __VA_ARGS__
#undef CONFIG_DEBUG_PESSIMIZE
#define ENABLE_DEBUG_PESSIMIZE 0
#define USE_DEBUG_PESSIMIZE(...)
#define SKIP_DEBUG_PESSIMIZE(...) __VA_ARGS__
#undef CONFIG_WERROR
#define ENABLE_WERROR 0
#define USE_WERROR(...)
#define SKIP_WERROR(...) __VA_ARGS__

/*
 * Installation Options
 */
#define CONFIG_PREFIX "./_install"
#define ENABLE_PREFIX 1
#define USE_PREFIX(...) __VA_ARGS__
#define SKIP_PREFIX(...)
