#define MODULE_NAME "BSP"
#define MAJOR_ID "00"
#define MINOR_ID "00"
#define RELEASE_COUNT "00"
#define P4_CL "$Change: 1466624 $"

char BSP_VERSION[50] = MODULE_NAME"-"MAJOR_ID"."MINOR_ID"."RELEASE_COUNT"."P4_CL;

