#ifndef __CYGCFG_FLAGS_DEF_H__
#define __CYGCFG_FLAGS_DEF_H__

//#define CYGCFG_FS_NTFS_MAXMEM_TRACK
//#define CYGCFG_FS_NTFS_QUICK_MOUNT

//#define CYGCFG_FS_NTFS_GET_INFO_FACTOR 1
//#define CYGCFG_FS_IO_BLOCK_NUM 512
//#define CYGCFG_FS_GETINFO_BORROW_BUF
#define CYGCFG_FS_FORMAT_PROGRESS

#endif
