# Copyright (c) 2008-2009 MStar Semiconductor, Inc.
# All rights reserved.
#
# AWK script to automatically generate uboot config file for module options


$2 == "ENABLE_USB" {print "#define ENABLE_MODULE_USB " $3}
$2 == "ENABLE_FAT" {print "#define ENABLE_MODULE_FAT " $3}
$2 == "ENABLE_USB_AUTO_UPDATE" {print "#define ENABLE_USB_AUTO_UPDATE " $3}
$2 == "ENABLE_NAND_FLASH" {print "#define ENABLE_MODULE_NAND_FLASH " $3}
$2 == "ENABLE_BFN_WRITE_NAND" {print "#define ENABLE_MODULE_BFN_WRITE_NAND " $3}
$2 == "ENABLE_FLASH" {print "#define ENABLE_MODULE_FLASH " $3}
$2 == "ENABLE_UBI" {print "#define ENABLE_MODULE_UBI " $3}
$2 == "ENABLE_UBI_FS" {print "#define ENABLE_MODULE_UBI_FS " $3}
$2 == "ENABLE_ENV_IN_UBI" {print "#define ENABLE_MODULE_ENV_IN_UBI " $3}
$2 == "ENABLE_ENV_IN_NAND" {print "#define ENABLE_MODULE_ENV_IN_NAND " $3}
$2 == "ENABLE_ENV_IN_MMC" {print "#define ENABLE_MODULE_ENV_IN_MMC " $3}
$2 == "ENABLE_ENV_IN_SERIAL" {print "#define ENABLE_MODULE_ENV_IN_SERIAL " $3}
$2 == "ENABLE_SECURITY_BOOT" {print "#define ENABLE_MODULE_SECURITY_BOOT " $3}
$2 == "ENABLE_NET" {print "#define ENABLE_MODULE_NET " $3}
$2 == "ENABLE_LWIP" {print "#define ENABLE_MODULE_LWIP " $3}
$2 == "ENABLE_USB_LAN" {print "#define ENABLE_MODULE_USB_LAN " $3}
$2 == "ENABLE_SPI" {print "#define ENABLE_MODULE_SPI " $3}
$2 == "ENABLE_EEPROM" {print "#define ENABLE_MODULE_EEPROM " $3}
$2 == "ENABLE_KEYPAD" {print "#define ENABLE_MODULE_KEYPAD " $3}
$2 == "ENABLE_STANDBY" {print "#define ENABLE_MODULE_STANDBY " $3}
$2 == "ENABLE_JFFS2" {print "#define ENABLE_MODULE_JFFS2 " $3}
$2 == "ENABLE_DISPLAY_LOGO" {print "#define ENABLE_MODULE_DISPLAY_LOGO " $3}
$2 == "ENABLE_MICOM" {print "#define ENABLE_MODULE_MICOM " $3}
$2 == "ENABLE_FRONT_END" {print "#define ENABLE_MODULE_FRONT_END " $3}
$2 == "ENABLE_MSTAR_MSB123x_DEMOD" {print "#define ENABLE_MODULE_DEMOD_MSTAR_MSB123x " $3}
$2 == "ENABLE_MSTAR_MSB122x_DEMOD" {print "#define ENABLE_MODULE_DEMOD_MSTAR_MSB122x " $3}
$2 == "ENABLE_DIBCOM_DIB8096_DEMOD" {print "#define ENABLE_MODULE_DEMOD_DIBCOM_DIB8096 " $3}
$2 == "ENABLE_LGDT3305_DEMOD" {print "#define ENABLE_MODULE_DEMOD_LGDT3305 " $3}
$2 == "ENABLE_MSTAR_TUNER_NUTUNE_FT2125" {print "#define ENABLE_MODULE_TUNER_NUTUNE_FT2125 " $3}
$2 == "ENABLE_MSTAR_TUNER_NUTUNE_FJ2207" {print "#define ENABLE_MODULE_TUNER_NUTUNE_FJ2207 " $3}
$2 == "ENABLE_MSTAR_TUNER_DIBCOM_DIB8096" {print "#define ENABLE_MODULE_TUNER_DIBCOM_DIB8096 " $3}
$2 == "ENABLE_TDVG_TUNER_H252F" {print "#define ENABLE_MODULE_TUNER_TDVG_H252F " $3}
$2 == "ENABLE_DEMO_CODE" {print "#define ENABLE_MODULE_DEMO_CODE " $3}
$2 == "ENABLE_WDT_ENABLE" {print "#define ENABLE_MODULE_WDT_ENABLE " $3}
$2 == "ENABLE_MSTAR_NAND" {print "#define ENABLE_MODULE_MSTAR_NAND " $3}
$2 == "ENABLE_MSTAR_TUNER_NXP_CD1616LF" {print "#define ENABLE_MODULE_TUNER_NXP_CD1616LF " $3}
$2 == "ENABLE_MSTAR_TUNER_NXP_TD1611ALF" {print "#define ENABLE_MODULE_TUNER_NXP_TD1611ALF " $3}
$2 == "ENABLE_MSTAR_TUNER_MXL_MXL5007" {print "#define ENABLE_MODULE_TUNER_MXL_MXL5007 " $3}
$2 == "ENABLE_MSTAR_TUNER_MXL201RF" {print "#define ENABLE_MODULE_TUNER_MXL201RF " $3}
$2 == "ENABLE_MSTAR_URANUS4_INTERNAL_DEMOD" {print "#define ENABLE_MODULE_DEMOD_URANUS4_INTERNAL " $3}
$2 == "ENABLE_MSTAR_KRONUS_INTERNAL_DEMOD" {print "#define ENABLE_MODULE_DEMOD_KRONUS_INTERNAL " $3}
$2 == "ENABLE_MSTAR_KAISERIN_INTERNAL_DEMOD" {print "#define ENABLE_MODULE_DEMOD_KAISERIN_INTERNAL " $3}
$2 == "ENABLE_MSTAR_KAPPA_INTERNAL_DEMOD" {print "#define ENABLE_MODULE_DEMOD_KAPPA_INTERNAL " $3}