#ifndef CYGONCE_PKGCONF_NET_FREEBSD_STACK_H
#define CYGONCE_PKGCONF_NET_FREEBSD_STACK_H
/*
 * File <pkgconf/net_freebsd_stack.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#include <pkgconf/net.h>
#define CYGINT_NET_IPSEC_BSD_CRYPTO 0
#define CYGINT_NET_IPSEC_BSD_CRYPTO_0
#define CYGPKG_NET_NGIF 0
#define CYGPKG_NET_NGIF_0
#define NGIF 0
#define NGIF_0
#define CYGPKG_NET_NLOOP 1
#define CYGPKG_NET_NLOOP_1
#define NLOOP 1
#define NLOOP_1
#define CYGPKG_NET_FREEBSD_LOGGING 0x0000C08F
#define CYGPKG_NET_FREEBSD_LOGGING_0x0000C08F
#define CYGPKG_NET_MEM_USAGE 278528
#define CYGPKG_NET_MEM_USAGE_278528
#define CYGPKG_NET_MEMPOOL_SIZE 69632
#define CYGPKG_NET_MEMPOOL_SIZE_69632
#define CYGPKG_NET_MBUFS_SIZE 69632
#define CYGPKG_NET_MBUFS_SIZE_69632
#define CYGPKG_NET_CLUSTERS_SIZE 139264
#define CYGPKG_NET_CLUSTERS_SIZE_139264
#define CYGPKG_NET_MAXSOCKETS 16
#define CYGPKG_NET_MAXSOCKETS_16
#define CYGPKG_NET_NUM_WAKEUP_EVENTS 8
#define CYGPKG_NET_NUM_WAKEUP_EVENTS_8
#define CYGPKG_NET_THREAD_PRIORITY 2
#define CYGPKG_NET_THREAD_PRIORITY_2
#define CYGPKG_NET_FAST_THREAD_PRIORITY 1
#define CYGPKG_NET_FAST_THREAD_PRIORITY_1

#endif
