
################################################################################
#
# Copyright (c) 2008-2009 MStar Semiconductor, Inc.
# All rights reserved.
#
# Unless otherwise stipulated in writing, any and all information contained
# herein regardless in any format shall remain the sole proprietary of
# MStar Semiconductor Inc. and be kept in strict confidence
# ("MStar Confidential Information") by the recipient.
# Any unauthorized act including without limitation unauthorized disclosure,
# copying, use, reproduction, sale, distribution, modification, disassembling,
# reverse engineering and compiling of the contents of MStar Confidential
# Information is unlawful and strictly prohibited. MStar hereby reserves the
# rights to any and all damages, losses, costs and expenses resulting therefrom.
#
#
# Makefile used for building application.
#
# The default target (all) builds application in three formats :
#   *.rec : Image in S-record format.
#   *.bin : Image in binary format.
#   *.elf : Image in ELF format.
#   *.map : Linker generated map file.
#   *.dis : Disassembly of image.
#   *.sym : Symbols.
#
# Other targets are :
#   clean :    Deletes all files generated by makefile.
#
#
################################################################################


# **********************************************
# Import configure file
# **********************************************
-include $(PRJ_DIR)/configure_mi
ifeq ($(MMSDK_BSP),enable)
DDI_MAIN_MMSDK_DIR = $(PRJ_DIR)/../../../../../../DDI_Main/mmsdk
-include  $(DDI_MAIN_MMSDK_DIR)/Makefile.mmsdk
endif

#disable as MI
#DDI_MAIN_DEMO_DIR = $(PRJ_DIR)/../../../../../../DDI_Main/demo
#include  $(DDI_MAIN_DEMO_DIR)/Makefile.demo

DDI_MISC_DIR = $(PRJ_DIR)/../../../../../../DDI_Misc
include  $(DDI_MISC_DIR)/cus_mstar/project/mstar_demo/Makefile

ifneq (,$(filter enable, $(DDI_CA_CONAX) $(DDI_CA_IRDETO) $(DDI_CA_NAGRA) ))
CA_ENABLE ?= enable
endif

ifeq ($(CA_ENABLE), enable)
export DDI_CA_DIR
export CA_ENABLE
export CA_CONAX
export CA_IRDETO
export CA_NAGRA
export CA_VMX
endif

ifeq ($(CA_ENABLE), enable)
DDI_CA_DIR ?= $(PRJ_DIR)/../../../../DDI_CA
-include $(DDI_CA_DIR)/ca_configuration
endif

# **********************************************
# Project specific
# **********************************************
ifneq ($(CA_CUSTOM_OS), enable)
ifeq ($(TOOLCHAIN),mips-linux-gnu)
OS_BUILT    = ecos_k1c_74kf_net_fileio_posix_fat_ntfs_v3_net_cpuload_c++_mipslinuxgnu
else
OS_BUILT    = ecos_k1c_74kf_net_fileio_posix_fat_ntfs_v3_net_cpuload_c++
endif
else
OS_BUILT=$(CA_OS_BUILT)
endif
CC_APPOPTS  =

# **********************************************
# Directories
# **********************************************
ROOT        = .
TRUNK       = ../../..
BSP_PRJ     = $(TRUNK)
CUS_TOP     = $(PRJ_DIR)/../../../..

DDI_MI_DIR ?= $(PRJ_DIR)/../../../../../../DDI_MI/V1.10

DDI_MAIN_MMSDK_DIR = $(PRJ_DIR)/../../../../../../DDI_Main/mmsdk

#set in set_env
DDI_MI_LIB= $(DDI_MI_DIR)/cus_mstar/mi/bin/libmi.a             \
            $(DDI_MI_DIR)/cus_mstar/mi/bin/libmidemo.a

# for QMAP
QMAP_SEL    = k1c_mstar

# NDS Verifier
SRCDIR     = \
            $(TRUNK)/cus_mstar/platform/driver/gmac           \
            $(TRUNK)/cus_mstar/platform/driver/pad             \
            $(TRUNK)/cus_mstar/platform/driver/pq              \
            $(TRUNK)/cus_mstar/platform/driver/pq/hal/$(QMAP_SEL)  \
            $(TRUNK)/cus_mstar/api/xc                          \
            $(TRUNK)/cus_mstar/api/sc                          \
            $(TRUNK)/cus_mstar/api/gpio                        \
            $(TRUNK)/cus_mstar/api/dte                        \
            $(TRUNK)/cus_mstar/api/mm/mmsdk			\
            $(TRUNK)/cus_mstar/api/lan

#SRCDIR     += $(TRUNK)/cus_mstar/platform/driver/jffs2
SRCDIR     += $(DDI_MISC_SRCDIR)

#SRCDIR     += $(TRUNK)/cus_mstar/api/xml/expat-2.0.1

ifeq ($(ATSC_CC_BSP),enable)
SRCDIR      += $(TRUNK)/cus_mstar/api/font
endif

#include DDI_Main source files
#SRCDIR     += $(DDI_MAIN_DEMO_SRCDIR)

#include DDI_MISC files
SRCDIR     += $(BSP_PRJ)/bsp/misc

PM_STR     =  $(PRJ_DIR)/pm

# Add version info c files
SRCDIR     += \
            $(TRUNK)/cus_mstar/platform/driver  \
            $(DDI_MISC_DIR)			\
            $(DDI_MAIN_DIR)

INCDIR     = \
            $(PRJ_DIR)                                              \
            $(PRJ_DIR)/include                                      \
            $(PRJ_DIR)/include/chip                                 \
            $(TRUNK)/cus_mstar/platform/driver/gmac           \
            $(TRUNK)/cus_mstar/platform/driver/pad             \
            $(TRUNK)/cus_mstar/platform/driver/pq/include      \
            $(TRUNK)/cus_mstar/platform/driver/pq/hal/$(QMAP_SEL)/include  \
            $(TRUNK)/cus_mstar/api/xc                          \
            $(TRUNK)/cus_mstar/api/sc                          \
            $(TRUNK)/cus_mstar/api/gpio                        \
            $(TRUNK)/cus_mstar/api/dte                        \
            $(TRUNK)/cus_mstar/api/mm/mmsdk			\
            $(TRUNK)/cus_mstar/api/lan                         \
            $(CUS_TOP)/cus_info/                               \

#INCDIR     += $(TRUNK)/cus_mstar/platform/driver/jffs2

#include DDI_Main include files
INCDIR     += $(DDI_MAIN_DEMO_INCDIR)

#include DDI_MISC files
INCDIR     += $(DDI_MISC_INCDIR)



ifeq ($(MMSDK_BSP), enable)
SRCDIR     += $(DDI_MAIN_MMSDK_SRCDIR)
INCDIR     += $(DDI_MAIN_MMSDK_INCDIR)

INCDIR     += \
            $(DDI_MISC_DIR)/cus_mstar/api/mwlibs_include/freetype/freetype2                    \
            $(DDI_MISC_DIR)/cus_mstar/api/mwlibs_include/freetype/freetype2/config            \
            $(DDI_MISC_DIR)/cus_mstar/api/mwlibs_include/iniparser            \
            $(TRUNK)/cus_mstar/api/mm/mmsdk/interface
endif

ifneq (,$(filter enable, $(SUBTITLE_BSP) $(CC_BSP) $(TTX_BSP) $(MMSDK_BSP)))
INCDIR     += \
            $(TRUNK)/cus_mstar/api/mm/fuchsia \
            $(TRUNK)/cus_mstar/api/mm/fuchsia/mm \
            $(TRUNK)/cus_mstar/api/mm/fuchsia/subtitle
endif

ifeq ($(PVR_BSP),enable)
INCDIR     += $(TRUNK)/cus_mstar/api/pvr
endif

ifeq ($(MI_ISDBT_CC_BSP),enable)
ifeq ($(ATSC_CC_BSP),enable)
INCDIR     += \
           $(TRUNK)/cus_mstar/api/cc_combine \
           $(TRUNK)/cus_mstar/api/font
else  #ATSC disable
INCDIR     += \
           $(TRUNK)/cus_mstar/api/cc
endif
else  # ISDBT_CC disable or undefine(backward compatible).
ifeq ($(ATSC_CC_BSP),enable)
INCDIR     += \
           $(TRUNK)/cus_mstar/api/atsc_cc \
           $(TRUNK)/cus_mstar/api/font
else  #ATSC disable
INCDIR     += \
           $(TRUNK)/cus_mstar/api/cc
endif
endif

ifeq ($(MI_IMGDEC_FEATURE),enable)
INCDIR     += $(TRUNK)/cus_mstar/api/image
endif
ifeq ($(CFG_CA),IRD)
SRCDIR     +=$(TRUNK)/verify/nds/ca_ird
INCDIR     +=$(TRUNK)/verify/nds/ca_ird
endif

ifeq ($(CFG_FE_AUTO_TEST), enable)
SRCDIR     += \
            $(DDI_MISC_CUS_DIR)/platform/driver/demod/autotest
INCDIR     += \
            $(DDI_MISC_CUS_DIR)/platform/driver/demod/autotest
endif

BINDIR      = bin
BIN_PATH    = $(ROOT)/$(BINDIR)
OBJDIR      = obj
OBJ_PATH    = $(ROOT)/$(OBJDIR)

# Search source file path
VPATH       = $(SRCDIR)                                       \
              $(DDI_MISC_CUS_DIR)/platform/driver/scart           \

ifeq ($(CA_ENABLE), enable)
-include $(DDI_CA_DIR)/Makefile.ca
SRCDIR += $(CA_SRCDIR)
INCDIR += $(CA_INCDIR)
SRC_C  += $(CA_SRC_C)
VPATH += $(CA_VPATH)
BSP_LIB += $(CA_BSP_LIB)
BSP_LIB_SHARED += $(CA_BSP_LIB_SHARED)
BSP_LIB_SHARED_PATH += $(CA_BSP_LIB_SHARED_PATH)
endif

# **********************************************
# Image file names
# **********************************************
IMAGE_BIN   = $(BIN_PATH)/$(IMAGENAME).bin
IMAGE_REC   = $(BIN_PATH)/$(IMAGENAME).rec
IMAGE_ELF   = $(BIN_PATH)/$(IMAGENAME).elf
IMAGE_MAP   = $(BIN_PATH)/$(IMAGENAME).map
IMAGE_DIS   = $(BIN_PATH)/$(IMAGENAME).dis
IMAGE_SIZ   = $(BIN_PATH)/$(IMAGENAME).siz
IMAGE_SYM   = $(BIN_PATH)/$(IMAGENAME).sym

# **********************************************
# Files to be compiled
# **********************************************
INC_C_LIB   = $(foreach dir, $(INCDIR_LIB),   $(wildcard $(dir)/*.h))
INC_C       = $(foreach dir, $(INCDIR),       $(wildcard $(dir)/*.h))
INC         = $(INC_C_LIB) $(INC_C)

#to be fixed, by teddy.chen
ifeq ('',$(findstring 'MST124', $(CFG_BOARD)))
SRC_C      += $(DDI_MISC_CUS_DIR)/platform/driver/scart/drvScart_STV6419.c
else
SRC_C      += $(DDI_MISC_CUS_DIR)/platform/driver/scart/drvScart_BD_MST.c
endif

SRC_C      += $(foreach dir, $(SRCDIR),       $(wildcard $(dir)/*.c))
SRC         = $(SRC_C)

OBJ_C_0     = $(notdir $(patsubst %.c, %.o,   $(SRC_C)))
OBJ_C       = $(foreach file, $(OBJ_C_0),     $(OBJ_PATH)/$(file))
OBJ         = $(OBJ_C)

# **********************************************
# Libraries
# **********************************************

# Standard Libraries Path
BSP_DIR     = $(BSP_PRJ)/bsp

# Middleware Libraries Path

# Libraries
#BSP_LIBS    = $(BSP_DIR)/lib/libdrvNDS.a # for testing TODO: fix it
BSP_LIBS   += $(wildcard $(BSP_DIR)/lib/libapi*.a)	# api lib
BSP_LIBS   += $(wildcard $(BSP_DIR)/lib/libdrv*.a)	# drv lib
BSP_LIBS   += $(BSP_DIR)/lib/lib$(OS_TYPE).a		# sys lib
BSP_LIBS   += $(BSP_DIR)/lib/libMsFS.a                  # MsFs lib
BSP_LIBS   += $(TRUNK)/cus_mstar/api/dte/libmsAPI_DTE.a # DTE lib
BSP_LIBS    += $(wildcard $(TRUNK)/cus_mstar/api/xc/*.a)	#Scaler/VE lib

#filter out libapiAUDIO*.a
#BSP_LIBS      := $(filter-out $(wildcard $(BSP_DIR)/lib/libapiAUDIO%),$(wildcard $(dir)/*.a))
BSP_LIBS         += $(foreach dir, $(BSP_DIR)/lib,  $(filter-out $(BSP_DIR)/lib/libapiAUDIO%, $(wildcard $(dir)/*.a)))

CPP_LIBS   += $(CFG_STDLIB_DIR)/libstdc++.a $(CFG_STDLIB_DIR)/libsupc++.a

#Choose to use MS10_1D/MS10_1D324/MS11 audio lib
ifeq ($(MI_AUDIO_REDUCE_TO_1D),enable)
AUDIO_LIB_DIR = $(BSP_DIR)/lib/audio/MS10_1D
else ifeq ($(MI_AUDIO_REDUCE_TO_1D_UNDERCLOCK_324MHZ),enable)
AUDIO_LIB_DIR = $(BSP_DIR)/lib/audio/MS10_1D324/
else
AUDIO_LIB_DIR = $(BSP_DIR)/lib/audio/MS11
endif

MI_AUDIO_LIB_DIR = $(PRJ_DIR)/$(AUDIO_LIB_DIR)
BSP_LIBS += $(AUDIO_LIB_DIR)/libapiAUDIO.a

ifeq ($(CFG_TVfunc),TVfunc_Normal)
NEW_AUDIO_LIB = $(BSP_DIR)/lib/libapiAUDIO_MpegSD.a
NEW_AUDSP_LIB = $(BSP_DIR)/lib/libdrvAUDSP_MpegSD.a
BSP_LIBS      := $(filter-out $(NEW_AUDIO_LIB) $(NEW_AUDSP_LIB), $(BSP_LIBS))
endif

ifeq ($(CFG_TVfunc),TVfunc_MpegSD)
OLD_AUDIO_LIB = $(BSP_DIR)/lib/libapiAUDIO.a
OLD_AUDSP_LIB = $(BSP_DIR)/lib/libdrvAUDSP.a
NEW_AUDIO_LIB = $(BSP_DIR)/lib/libapiAUDIO_MpegSD.a
NEW_AUDSP_LIB = $(BSP_DIR)/lib/libdrvAUDSP_MpegSD.a
BSP_LIBS      := $(filter-out $(OLD_AUDIO_LIB) $(OLD_AUDSP_LIB), $(BSP_LIBS))
BSP_LIBS      += $(NEW_AUDIO_LIB) $(NEW_AUDSP_LIB)
endif

ifeq ($(CFG_TVfunc),H264SD)
OLD_AUDIO_LIB = $(BSP_DIR)/lib/libapiAUDIO.a
OLD_AUDSP_LIB = $(BSP_DIR)/lib/libdrvAUDSP.a
NEW_AUDIO_LIB = $(BSP_DIR)/lib/libapiAUDIO_MpegSD.a
NEW_AUDSP_LIB = $(BSP_DIR)/lib/libdrvAUDSP_MpegSD.a
BSP_LIBS      := $(filter-out $(OLD_AUDIO_LIB) $(OLD_AUDSP_LIB), $(BSP_LIBS))
BSP_LIBS      += $(NEW_AUDIO_LIB) $(NEW_AUDSP_LIB)
endif

ifeq ($(DAPI_BSP), enable)
ifeq ($(DAPI_DELAY_TASK_WRAP_BSP), enable)
BSP_LIBS += -Wl,--wrap,MsOS_DelayTask
endif
ifeq ($(DAPI_MEM_FENCE_BSP), enable)
BSP_LIBS += -Wl,--wrap,MsOS_AllocateMemory,--wrap,MsOS_FreeMemory
endif
endif

ifeq ($(MM_BSP),enable)
BSP_LIBS   += $(wildcard $(TRUNK)/cus_mstar/api/mm/*.a)      # mm lib
BSP_LIBS   += $(wildcard $(TRUNK)/cus_mstar/api/mm/vdplayer/*.a)
BSP_LIBS   += $(wildcard $(DDI_MISC_DIR)/cus_mstar/api/mm/freetype/*.a)
BSP_LIBS   += $(wildcard $(DDI_MISC_DIR)/cus_mstar/api/mm/iniparser/*.a)
BSP_LIBS   += $(wildcard $(TRUNK)/cus_mstar/api/mm/mmsdk/*.a)
endif

ifneq (,$(filter enable, $(SUBTITLE_BSP) $(CC_BSP) $(TTX_BSP) $(MM_BSP)))
BSP_LIBS   += $(wildcard $(TRUNK)/cus_mstar/api/mm/fuchsia/*.a)
endif

ifeq ($(MI_IMGDEC_FEATURE), enable)
BSP_LIBS   += $(wildcard $(TRUNK)/cus_mstar/api/image/*.a)
endif

ifeq ($(PVR_BSP),enable)
BSP_LIBS   += $(wildcard $(TRUNK)/cus_mstar/api/pvr/*.a)      # pvr lib
endif

ifeq ($(TTX_BSP),enable)
BSP_LIBS   += $(wildcard $(TRUNK)/cus_mstar/api/ttx/libmwttx.a)      # ttx lib
endif

ifeq ($(MI_ISDBT_CC_BSP), enable)
ifeq ($(ATSC_CC_BSP),enable)
BSP_LIBS         += $(foreach dir, $(TRUNK)/cus_mstar/api/cc_combine, $(wildcard $(dir)/*.a))
else   # ATSC disable, ISDBT enable
BSP_LIBS         += $(foreach dir, $(TRUNK)/cus_mstar/api/cc, $(wildcard $(dir)/*.a))
endif
else   # ISDBT_CC disable or undefine(backward compatible).
ifeq ($(ATSC_CC_BSP),enable)
BSP_LIBS         += $(foreach dir, $(TRUNK)/cus_mstar/api/atsc_cc, $(wildcard $(dir)/*.a))
else
BSP_LIBS         += $(foreach dir, $(TRUNK)/cus_mstar/api/cc, $(wildcard $(dir)/*.a))
endif
endif

ifeq ($(MI_WLAN), enable)
WIFI_LIB_PATH     = $(DDI_MISC_DIR)/cus_mstar/platform/driver/wlan/mt7601u/lib
BSP_LIBS         += $(WIFI_LIB_PATH)/$(TOOLCHAIN)/$(TOOLCHAIN_VERSION)/libdrvECOS_USBWIFI.a
endif

# Middlware Libraries
ifeq ($(CFG_CA),NDS)
ifeq ($(CFG_NDS_LIB),NDS)
MW_LIBS     = $(TRUNK)/verify/nds/tstver_mstar_dv.a
endif
endif
ifeq ($(CFG_CA),TF)
MW_LIBS     = $(TRUNK)/verify/nds/MSD5015-20080429D.lib
endif
ifeq ($(CFG_CA),IRD)
MW_LIBS     = $(TRUNK)/verify/nds/s3_dvb_client_3.3.9.lib
endif
ifeq ($(CFG_CA),NGA)
MW_LIBS     =
endif


# **********************************************
# Compiler and linker options
# **********************************************
ifeq ($(OS_TYPE),ecos)
ifneq ($(CA_CUSTOM_OS), enable)
OS_INC_DIR  = $(TRUNK)/$(OS_TYPE)/$(OS_BUILT)/include
OS_INC_DIR  += $(TRUNK)/$(OS_TYPE)/$(OS_BUILT)/include/linux

OS_LIB_DIR  = $(TRUNK)/$(OS_TYPE)/$(OS_BUILT)/lib
OS_LIBS = $(wildcard $(OS_LIB_DIR)/*.a)
OS_EX_BUILD_OBJ = $(wildcard $(TRUNK)/$(OS_TYPE)/$(OS_BUILT)/libntfs/*.o)
#OS_EX_BUILD_OBJ += $(wildcard $(TRUNK)/$(OS_TYPE)/$(OS_BUILT)/libjffs2/*.o)
else
OS_INC_DIR=$(CA_OS_INC_DIR)
OS_LIB_DIR=$(CA_OS_LIB_DIR)
OS_EX_BUILD_OBJ=$(CA_OS_EX_BUILD_OBJ)
endif
endif
ifeq ($(OS_TYPE),ucos)
OS_INC_DIR  = $(TRUNK)/$(OS_TYPE)/include
OS_LIB_DIR  = $(TRUNK)/$(OS_TYPE)/lib
endif

ALL_INC_DIR = $(OS_INC_DIR) $(INCDIR) $(BSP_DIR)/include $(BSP_DIR)/lib/fw

CC_INCS     = $(foreach dir, $(ALL_INC_DIR), -I$(dir))

CC_DEFS     = $(CFG_CC_DEFS)
# GCC options:
CC_OPTS     = $(CFG_CC_OPTS) -Wall -Wpointer-arith -Wstrict-prototypes -Winline -Wundef
CC_OPTS    += -fno-strict-aliasing -fno-optimize-sibling-calls -fno-exceptions -fno-builtin
CC_OPTS    += -ffunction-sections
CC_OPTS    += -fdata-sections
CC_OPTS    += -c -G0

ifeq ($(BLT_TYPE),debug)
CC_OPTS    += -O0
CC_DEFS    += -D'MS_DEBUG'
else
CC_OPTS    += -Os
CC_DEFS    += -D'MS_OPTIMIZE'
endif

ifeq ($(CA_ENABLE), enable)
CC_OPTS    += $(CA_CC_OPTS)
CXX_OPTS   += $(CA_CXX_OPTS)
endif

# AS options:
AS_OPTS     = -mips32 -$(ENDIAN) -G0 -O2 -gdwarf2


# LD options:
ifneq ($(CA_CUSTOM_LD), enable)
ifeq ($(TOOLCHAIN),mips-sde-elf)
LD_SCRIPT   = ecos_mipssde.ld
endif
ifeq ($(TOOLCHAIN),mipsisa32-elf)
LD_SCRIPT   = ecos_mipsisa32.ld
endif
ifeq ($(TOOLCHAIN),mips-linux-gnu)
LD_SCRIPT   = ecos_mipslinuxgnu.ld
endif
else
LD_SCRIPT   = $(CA_LD_SCRIPT)
endif
LD_LIBS     = -L$(OS_LIB_DIR) -L$(CFG_STDLIB_DIR) -L$(BSP_DIR)/lib -T$(LD_SCRIPT) # libtarget.a, libgcc.a, UART+EMAC
#LD_OPTS     = $(CFG_LD_OPTS) -nostdlib -$(ENDIAN) --gc-sections -static -Map $(IMAGE_MAP)
LD_OPTS     = $(CFG_LD_OPTS) -$(ENDIAN) --gc-sections -static -Map $(IMAGE_MAP)

ifeq ($(MI_BSP_LIB_RELEASE),enable)
export TMP_LIB = $(PRJ_DIR)/autogen
LD_OPTS += -L$(TMP_LIB)
RELEASE_BSP_TMP_LIB += $(TMP_LIB)/libBSP.a
endif

# Force put VERSION symbols into output file
ifneq ("$(wildcard $(DDI_MAIN_DIR)/*version_info.c)","")
LD_OPTS += -u DDI_MAIN_VERSION
endif
ifneq ("$(wildcard $(DDI_MISC_DIR)/*version_info.c)","")
LD_OPTS += -u DDI_MISC_VERSION
endif
ifneq ("$(wildcard $(TRUNK)/cus_mstar/platform/driver/*version_info.c)","")
LD_OPTS += -u BSP_VERSION
endif

LIBGCC = $(CFG_STDLIB_DIR)/libgcc.a

# **********************************************
# Rules
# **********************************************
.PHONY : all clean library package depend $(IMAGE_ELF)

# Project Build
all : setup caBuildLib makeImg

makeElf : $(IMAGE_ELF)

makeMI :
ifeq ($(MI_PM_STANDBY_MODE),1)
	@cp -f $(PRJ_DIR)/pmlite_sram.dat $(DDI_MI_DIR)/cus_mstar/app/mi_demo/mi_pmlite_sram1.dat
	@echo "Copy PM code raw data to MI...";
else
	@cp -f $(PM_STR)/pmlite_str.dat $(DDI_MI_DIR)/cus_mstar/app/mi_demo/mi_pmlite_sram1.dat
	@echo "Copy PM code STR raw data to MI...";
endif
	@touch -a $(DDI_MI_DIR)/cus_mstar/app/mi_demo/mi_pmlite_sram2.dat
	@$(MAKE) -C $(DDI_MI_DIR)/cus_mstar/mi setup DDI_DIR=${PWD}/../../..
	@$(MAKE) -C $(DDI_MI_DIR)/cus_mstar/mi DDI_DIR=${PWD}/../../.. DDI_MISC_DIR=$(DDI_MISC_DIR) OS_BUILT=$(OS_BUILT) MI_AUDIO_LIB_DIR=$(MI_AUDIO_LIB_DIR)
	@rm -f $(DDI_MI_DIR)/cus_mstar/app/mi_demo/mi_pmlite_sram1.dat
	@rm -f $(DDI_MI_DIR)/cus_mstar/app/mi_demo/mi_pmlite_sram2.dat
ifeq ($(MI_WLAN), enable)
	@rm -f $(WIFI_LIB_PATH)/$(TOOLCHAIN)/$(TOOLCHAIN_VERSION)/libdrvECOS_USBWIFI.a
	@ln -s $(WIFI_LIB_PATH)/$(TOOLCHAIN)/$(TOOLCHAIN_VERSION)/mips32/libdrvECOS_USBWIFI.a $(WIFI_LIB_PATH)/$(TOOLCHAIN)/$(TOOLCHAIN_VERSION)/libdrvECOS_USBWIFI.a
endif

# makeImg : $(IMAGE_ELF) $(IMAGE_BIN)
makeImg : $(OBJ_C) makeMI $(IMAGE_ELF) $(IMAGE_BIN)

# Note: It's slow to produce .dis file w/o -gdwarf-2 set or original OS source code
makeImgInfo : $(IMAGE_ELF)
	$(OBJDUMP) -S $(IMAGE_ELF) > $(IMAGE_DIS);
	$(SIZE) $(IMAGE_ELF) > $(IMAGE_SIZ);
	$(NM) -a -S $(IMAGE_ELF) > $(IMAGE_SYM);

# Utility makefile for standalone library
makeFont : fontsetup fontlib

# Project Image Build

# Project Image Build
$(IMAGE_BIN) : $(IMAGE_ELF)
	$(OBJCOPY) -O binary $(IMAGE_ELF) $(IMAGE_BIN);

ifeq ($(MI_BSP_LIB_RELEASE),enable)
$(IMAGE_ELF) :
	@echo '  [LD] $@'
	@$(LD) -G0 $(CA_SHARED_LIB_LD_OPTS) $(LD_OPTS) -o $(IMAGE_ELF) $(OBJ_C) $(LD_LIBS) --start-group $(RELEASE_BSP_TMP_LIB) $(OS_LIBS) $(OS_EX_BUILD_OBJ) $(DDI_MI_LIB) $(CPP_LIBS) $(LIBGCC) --end-group $(MW_LIBS) $(FONT_LIB) $(CA_BSP_LIB);
else
ifeq ($(PVR_BSP),enable)
$(IMAGE_ELF) :
	@echo '  [LD] $@'
	@$(LD) -G0 $(CA_SHARED_LIB_LD_OPTS) $(LD_OPTS) -o $(IMAGE_ELF) $(OBJ_C) $(LD_LIBS) --start-group $(BSP_LIBS) $(OS_LIBS) $(OS_EX_BUILD_OBJ) $(DDI_MI_LIB) $(CPP_LIBS) $(LIBGCC) --end-group $(MW_LIBS) $(FONT_LIB) $(CA_BSP_LIB);
else ifeq ($(MM_BSP),enable)
$(IMAGE_ELF) :
	@echo '  [LD] $@'
	@$(LD) -G0 $(CA_SHARED_LIB_LD_OPTS) $(LD_OPTS) -o $(IMAGE_ELF) $(OBJ_C) $(LD_LIBS) --start-group $(BSP_LIBS) $(OS_LIBS) $(OS_EX_BUILD_OBJ) $(DDI_MI_LIB) $(CPP_LIBS) $(LIBGCC) --end-group $(MW_LIBS) $(FONT_LIB) $(CA_BSP_LIB);
else
$(IMAGE_ELF) :
	@echo '  [LD] $@'
	@$(LD) $(CA_SHARED_LIB_LD_OPTS) $(LD_OPTS) -o $(IMAGE_ELF) $(OBJ_C) $(LD_LIBS) --start-group $(BSP_LIBS) $(OS_LIBS) $(OS_EX_BUILD_OBJ) $(DDI_MI_LIB) $(CPP_LIBS) $(LIBGCC) --end-group $(MW_LIBS) $(FONT_LIB) $(CA_BSP_LIB);
endif
endif

# Project Source Build
$(OBJ_C) : $(OBJ_PATH)/%.o : %.c
	@echo '  [CC] $@'
	@$(CC) $(CC_OPTS) $(CC_DEFS) $(CC_INCS) -o $@ $<;

# Project Setup
setup : setup_sca
	-@mkdir -p $(OBJDIR) 2> /dev/null;
	-@mkdir -p $(BINDIR) 2> /dev/null;
#	@cp $(PRJ_DIR)/pmlite_str.dat $(DDI_MI_DIR)/cus_mstar/app/mi_demo/mi_pmlite_sram1.dat
#	@cp $(PRJ_DIR)/pmlite_str.dat $(DDI_MI_DIR)/cus_mstar/app/mi_demo/mi_pmlite_sram2.dat
	@echo "Make $(CHIP) $(PROJNAME) project...";
ifneq ($(CA_SKIP_HARDFLOAT_CHECK),enable)
ifeq ($(TOOLCHAIN),mipsisa32-elf)
	@k=0; for i in $(BSP_LIBS); do j=`$(AR) t $$i | grep -ic 'hardfloat'`; if(($$j==0)); then k=1;echo $$i" use soft-float! Please use hard-float instead."; fi ; done ; if((k>0)); then false ; fi
endif
endif

menuconfigMI :
	@echo "run menuconfig for MI"
	@$(MAKE) -C $(DDI_MI_DIR)/cus_mstar/mi menuconfigMI

ifeq ($(MI_SYS_MMAP_MODE), sca)
#1. Translate $(CHIP) all to lower case. ex:kenya
#2. Translate first char to Upper case. ex:Kenya
CHIP_NAME = $(shell echo $(CHIP) | sed 's/[A-Z]/\L&/g' | sed -n 's/^[a-z]/\U&/p' )
  ifeq ($(MI_AUDIO_REDUCE_TO_1D),enable)
    SCA_FILE = MMAP_MI_$(CHIP_NAME)_64.h
  else
    ifeq ($(CFG_MEMORY_MAP),MMAP_64MB)
        SCA_FILE = MMAP_MI_$(CHIP_NAME)_64.h
    else ifeq ($(CFG_MEMORY_MAP),MMAP_128MB)
        SCA_FILE = MMAP_MI_$(CHIP_NAME)_128.h
    else ifeq ($(CFG_MEMORY_MAP),MMAP_256MB)
        SCA_FILE = MMAP_MI_$(CHIP_NAME)_256.h
    else ifeq ($(CFG_MEMORY_MAP),MMAP_512MB)
        SCA_FILE = MMAP_MI_$(CHIP_NAME)_512.h
    else ifeq ($(CFG_MEMORY_MAP),MMAP_128MB_128MB)
        SCA_FILE = MMAP_MI_$(CHIP_NAME)_128_128.h
    endif
  endif


setup_sca :
	@echo SCA_FILE=$(SCA_FILE)
	@cp $(SCA_FILE) MMAP_MI.h
else
setup_sca :
endif


# Project Clean
clean : caClean
	@echo "Clean $(CHIP) $(PROJNAME) project..."
	@rm -f -r $(OBJ_PATH)
	@rm -f -r $(BIN_PATH)
	@rm -f -r $(DDI_MI_DIR)/cus_mstar/app/mi_demo/pmlite_sram.dat
	@echo "Clean $(CHIP) $(PROJNAME) ..."
	@$(MAKE) -C $(DDI_MI_DIR)/cus_mstar/mi clean

# Project Dependence
depend :
	$(CC) $(CC_OPTS) $(CC_DEFS) $(CC_INCS) -M $(SRC) > $(BIN_PATH)/depend.mk


# Project Dependence Full version
dep :
	$(CC) $(CC_OPTS) $(CC_DEFS) $(CC_INCS) -M $(SRC) > $(BIN_PATH)/depend.mk
	cat $(BIN_PATH)/depend.mk | sed -e 's/\(.*\)\.o/\$$\(OBJ_PATH\)\/\1.o/g' > depend.mk


-include depend.mk

ifeq ($(CA_ENABLE), enable)
-include $(DDI_CA_DIR)/Makefile.ca.target
else
caBuildLib:
	@echo "caBuildLib do nothing..."

caPrepareLib:
	@echo "caPrepareLib do nothing..."

caAutoGen:
	@echo "caAutoGen do nothing..."

caClean:
	@echo "caClean do nothing..."

endif # end ifeq($(CA_ENABLE)...
