# ****************************************
# TDAL_ANA_AUD makefile
# ****************************************
include $(TDAL_MAKE)/environnement.mak
include $(SDK_ROOT)/drivers.mak

# ****************************************
# Define module name
# ****************************************
MODULE  = tbox

# ****************************************
# This define the default command for gmake
# ****************************************
all: $(LIB_PREFFIX)$(MODULE).$(LIB_SUFFIX)

# ****************************************
# Include paths needed to compile those files
# ****************************************
DIR_INCLUDE =

# ***************************************************
# List of object files needed to create library
# ***************************************************
LIBOBJS = 	

# ****************************************
# List of dependencies
# ****************************************

# ****************************************
# Always include crules.mak
# ****************************************
include $(TDAL_MAKE)/crules.mak
