#ifndef _FRONTEND_CONFIG_H_
#define _FRONTEND_CONFIG_H_

#include <config.h>

/*
#define ENABLE_DVB_T_SYS 0
#define ENABLE_ISDB_T_SYS 0
#define ENABLE_DVB_C_SYS 1
#define ENABLE_DVB_S_SYS 0
#define ENABLE_DVB_S2_SYS 0
#define ENABLE_DVB_T2_SYS 0
#define ENABLE_ATSC_SYS 0
*/

#ifdef FRONTEND_TUNER_TYPE
#undef FRONTEND_TUNER_TYPE
#endif

#ifdef FRONTEND_DEMOD_TYPE
    #undef FRONTEND_DEMOD_TYPE
#endif
   
#if (ENABLE_TUNER_AV2011)
#define FRONTEND_TUNER_TYPE TUNER_AV2011

#elif (ENABLE_MSTAR_TUNER_AV2012)
#define FRONTEND_TUNER_TYPE TUNER_AV2012

#elif (ENABLE_MODULE_TUNER_NXP_CD1616LF)
#define FRONTEND_TUNER_TYPE NXP_CD1616LF_TUNER

#elif (ENABLE_MSTAR_TUNER_PHILIPS_CD1616LF_GIGH_4)
#define FRONTEND_TUNER_TYPE NXP_TD1611ALF_TUNER

#elif (ENABLE_MSTAR_TUNER_NuTune_FT2125)
#define FRONTEND_TUNER_TYPE TUNER_NuTune_FT2125

#elif (ENABLE_MSTAR_TUNER_RT828)
#define FRONTEND_TUNER_TYPE TUNER_RT828

#elif (ENABLE_MSTAR_TUNER_MXL201RF)
#define FRONTEND_TUNER_TYPE TUNER_MXL201RF

#elif (ENABLE_MSTAR_TUNER_MXL603)
#define FRONTEND_TUNER_TYPE TUNER_MXL603

#elif (ENABLE_MSTAR_TUNER_MXL_MXL5007)
#define FRONTEND_TUNER_TYPE MXL_MXL5007_TUNER


#elif (ENABLE_MSTAR_TUNER_THOMSON_DCT70707)
#define FRONTEND_TUNER_TYPE TUNER_THOMSON_DCT70707

#elif (ENABLE_MSTAR_TUNER_PHILIPS_TDA18250HN)
#define FRONTEND_TUNER_TYPE TUNER_PHILIPS_TDA18250HN

#elif (ENABLE_MSTAR_TUNER_NMI120)
#define FRONTEND_TUNER_TYPE TUNER_NMI120

#elif (ENABLE_MSTAR_TUNER_LG_TDVG_H252F)
#define FRONTEND_TUNER_TYPE TUNER_LG_TDVG_H252F

#elif (ENABLE_MSTAR_TUNER_RT820T)
#define FRONTEND_TUNER_TYPE TUNER_RT820T

#elif ENABLE_MSTAR_TUNER_MXL201RF
#define FRONTEND_TUNER_TYPE TUNER_MXL201RF

#elif ENABLE_MSTAR_TUNER_MXL_MXL603
#define FRONTEND_TUNER_TYPE TUNER_MXL603 

#endif


//##################################################################
//@DEMOD CONFIG FOR PLATFORM
//##################################################################
//#define FRONTEND_DEMOD_TYPE DEMOD_MSB123X

#if (ENABLE_DEMOD_AVL6211)
#define FRONTEND_DEMOD_TYPE DEMOD_AVL6211

#elif (ENABLE_MODULE_DEMOD_URANUS4_INTERNAL)
#define FRONTEND_DEMOD_TYPE EMBEDDED_DVBC_DEMOD

#elif(ENABLE_MSTAR_MSB123x_DEMOD)
#define FRONTEND_DEMOD_TYPE MSTAR_MSB123x_DEMOD

#elif(ENABLE_MSTAR_MSB1236C_DEMOD)
#define FRONTEND_DEMOD_TYPE MSTAR_MSB1236C_DEMOD

#elif(ENABLE_MSTAR_MSB131X_DEMOD)
#define FRONTEND_DEMOD_TYPE MSTAR_MSB131X_DEMOD 
#elif ((ENABLE_MSTAR_KAPPA_INTERNAL_DEMOD  || ENABLE_MSTAR_KRITI_INTERNAL_DEMOD ||ENABLE_MSTAR_KRONUS_INTERNAL_DEMOD) && ENABLE_DVB_T_SYS)
#define FRONTEND_DEMOD_TYPE EMBEDDED_DVBT51_DEMOD
#elif ((ENABLE_MSTAR_KRONUS_INTERNAL_DEMOD || ENABLE_MSTAR_KAPPA_INTERNAL_DEMOD || ENABLE_MSTAR_KRITI_INTERNAL_DEMOD) && ENABLE_DVB_C_SYS)
#define FRONTEND_DEMOD_TYPE EMBEDDED_DVBC51_DEMOD

#elif (ENABLE_DEMOD_ATBM885x)    
#define FRONTEND_DEMOD_TYPE DEMOD_ATBM885x

#elif ENABLE_DEMOD_SamSung_S5H1411
#define FRONTEND_DEMOD_TYPE   DEMOD_SamSung_S5H1411

#elif ENABLE_MSTAR_MSB1400_DEMOD
#define FRONTEND_DEMOD_TYPE MSTAR_MSB1400_DEMOD

#endif
/*#ifdef FRONTEND_DEMOD_TYPE
#undef FRONTEND_DEMOD_TYPE
#endif

#ifdef FRONTEND_TUNER_TYPE
#undef FRONTEND_TUNER_TYPE
#endif*/
//dvbc
//#define FRONTEND_DEMOD_TYPE EMBEDDED_DVBC51_DEMOD
//#define FRONTEND_TUNER_TYPE TUNER_THOMSON_DCT70707
//dvbt
//#define MXL_MXL5007_TUNER 89
//#define EMBEDDED_DVBT51_DEMOD 14
//#define FRONTEND_DEMOD_TYPE EMBEDDED_DVBT51_DEMOD
//#define FRONTEND_TUNER_TYPE MXL_MXL5007_TUNER
//isdb_t
//#define FRONTEND_DEMOD_TYPE MSTAR_MSB1400_DEMOD
//#define FRONTEND_TUNER_TYPE TUNER_RT820T
//dvb_t2
//#define FRONTEND_TUNER_TYPE TUNER_MXL201RF
//#define FRONTEND_DEMOD_TYPE MSTAR_MSB123x_DEMOD
//dvbs
//#define FRONTEND_TUNER_TYPE TUNER_AV2012
//#define FRONTEND_DEMOD_TYPE MSTAR_MSB131X_DEMOD





          

#endif
