////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSD7R134D_H_
#define _MSD7R134D_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_C1 PAD_SAR_GPIO0
#define PAD_SAR_GPIO0 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_C1_IS_GPIO
#define BALL_C1_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO0_IS_GPIO
#define PAD_SAR_GPIO0_IS_GPIO BALL_C1_IS_GPIO
#endif 

#define BALL_C2 PAD_SAR_GPIO1
#define PAD_SAR_GPIO1 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_C2_IS_GPIO
#define BALL_C2_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO1_IS_GPIO
#define PAD_SAR_GPIO1_IS_GPIO BALL_C2_IS_GPIO
#endif 

#define BALL_D3 PAD_SAR_GPIO2
#define PAD_SAR_GPIO2 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_D3_IS_GPIO
#define BALL_D3_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO2_IS_GPIO
#define PAD_SAR_GPIO2_IS_GPIO BALL_D3_IS_GPIO
#endif 

#define BALL_G3 PAD_VPLUG_DET
#define PAD_VPLUG_DET 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_G3_IS_GPIO
#define BALL_G3_IS_GPIO 0
#endif 
#ifndef PAD_VPLUG_DET_IS_GPIO
#define PAD_VPLUG_DET_IS_GPIO BALL_G3_IS_GPIO
#endif 

#define BALL_B2 PAD_PM_GPIO9
#define PAD_PM_GPIO9 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO9_IS_GPIO
#define PAD_PM_GPIO9_IS_GPIO BALL_B2_IS_GPIO
#endif 

#define BALL_B1 PAD_PM_GPIO10
#define PAD_PM_GPIO10 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_B1_IS_GPIO
#define BALL_B1_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO10_IS_GPIO
#define PAD_PM_GPIO10_IS_GPIO BALL_B1_IS_GPIO
#endif 

#define BALL_E2 PAD_PM_GPIO12
#define PAD_PM_GPIO12 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_E2_IS_GPIO
#define BALL_E2_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO12_IS_GPIO
#define PAD_PM_GPIO12_IS_GPIO BALL_E2_IS_GPIO
#endif 

#define BALL_E1 PAD_PM_GPIO13
#define PAD_PM_GPIO13 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_E1_IS_GPIO
#define BALL_E1_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO13_IS_GPIO
#define PAD_PM_GPIO13_IS_GPIO BALL_E1_IS_GPIO
#endif 

#define BALL_E4 PAD_PM_GPIO0
#define PAD_PM_GPIO0 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO0_IS_GPIO
#define PAD_PM_GPIO0_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define BALL_F3 PAD_PM_GPIO1
#define PAD_PM_GPIO1 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_F3_IS_GPIO
#define BALL_F3_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO1_IS_GPIO
#define PAD_PM_GPIO1_IS_GPIO BALL_F3_IS_GPIO
#endif 

#define BALL_D4 PAD_PM_GPIO4
#define PAD_PM_GPIO4 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO4_IS_GPIO
#define PAD_PM_GPIO4_IS_GPIO BALL_D4_IS_GPIO
#endif 

#define BALL_D2 PAD_PM_IRIN
#define PAD_PM_IRIN 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_D2_IS_GPIO
#define BALL_D2_IS_GPIO 0
#endif 
#ifndef PAD_PM_IRIN_IS_GPIO
#define PAD_PM_IRIN_IS_GPIO BALL_D2_IS_GPIO
#endif 

#define BALL_K2 PAD_PM_SPI_RSTZ
#define PAD_PM_SPI_RSTZ 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_K2_IS_GPIO
#define BALL_K2_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_RSTZ_IS_GPIO
#define PAD_PM_SPI_RSTZ_IS_GPIO BALL_K2_IS_GPIO
#endif 

#define BALL_K1 PAD_PM_SPI_WPZ
#define PAD_PM_SPI_WPZ 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_K1_IS_GPIO
#define BALL_K1_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_WPZ_IS_GPIO
#define PAD_PM_SPI_WPZ_IS_GPIO BALL_K1_IS_GPIO
#endif 

#define BALL_J1 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_J1_IS_GPIO
#define BALL_J1_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_J1_IS_GPIO
#endif 

#define BALL_J3 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_J3_IS_GPIO
#define BALL_J3_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_J3_IS_GPIO
#endif 

#define BALL_K3 PAD_PM_GPIO14
#define PAD_PM_GPIO14 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_K3_IS_GPIO
#define BALL_K3_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO14_IS_GPIO
#define PAD_PM_GPIO14_IS_GPIO BALL_K3_IS_GPIO
#endif 

#define BALL_H2 PAD_PM_SPI_HOLDZ
#define PAD_PM_SPI_HOLDZ 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_H2_IS_GPIO
#define BALL_H2_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_HOLDZ_IS_GPIO
#define PAD_PM_SPI_HOLDZ_IS_GPIO BALL_H2_IS_GPIO
#endif 

#define BALL_J2 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_J2_IS_GPIO
#define BALL_J2_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_J2_IS_GPIO
#endif 

#define BALL_H1 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_H1_IS_GPIO
#define BALL_H1_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_H1_IS_GPIO
#endif 

#define BALL_G2 PAD_TM_GPIO0
#define PAD_TM_GPIO0 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_G2_IS_GPIO
#define BALL_G2_IS_GPIO 0
#endif 
#ifndef PAD_TM_GPIO0_IS_GPIO
#define PAD_TM_GPIO0_IS_GPIO BALL_G2_IS_GPIO
#endif 

#define BALL_H3 PAD_TM_GPIO1
#define PAD_TM_GPIO1 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_H3_IS_GPIO
#define BALL_H3_IS_GPIO 0
#endif 
#ifndef PAD_TM_GPIO1_IS_GPIO
#define PAD_TM_GPIO1_IS_GPIO BALL_H3_IS_GPIO
#endif 

#define BALL_R11 PAD_SM0_CLK
#define PAD_SM0_CLK 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_R11_IS_GPIO
#define BALL_R11_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CLK_IS_GPIO
#define PAD_SM0_CLK_IS_GPIO BALL_R11_IS_GPIO
#endif 

#define BALL_N13 PAD_SM0_RST
#define PAD_SM0_RST 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_N13_IS_GPIO
#define BALL_N13_IS_GPIO 0
#endif 
#ifndef PAD_SM0_RST_IS_GPIO
#define PAD_SM0_RST_IS_GPIO BALL_N13_IS_GPIO
#endif 

#define BALL_P14 PAD_SM0_C4
#define PAD_SM0_C4 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_P14_IS_GPIO
#define BALL_P14_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C4_IS_GPIO
#define PAD_SM0_C4_IS_GPIO BALL_P14_IS_GPIO
#endif 

#define BALL_P13 PAD_SM0_IO
#define PAD_SM0_IO 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_P13_IS_GPIO
#define BALL_P13_IS_GPIO 0
#endif 
#ifndef PAD_SM0_IO_IS_GPIO
#define PAD_SM0_IO_IS_GPIO BALL_P13_IS_GPIO
#endif 

#define BALL_R14 PAD_SM0_C8
#define PAD_SM0_C8 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_R14_IS_GPIO
#define BALL_R14_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C8_IS_GPIO
#define PAD_SM0_C8_IS_GPIO BALL_R14_IS_GPIO
#endif 

#define BALL_R13 PAD_SM0_CD
#define PAD_SM0_CD 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_R13_IS_GPIO
#define BALL_R13_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CD_IS_GPIO
#define PAD_SM0_CD_IS_GPIO BALL_R13_IS_GPIO
#endif 

#define BALL_N12 PAD_SM0_GPIO
#define PAD_SM0_GPIO 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_N12_IS_GPIO
#define BALL_N12_IS_GPIO 0
#endif 
#ifndef PAD_SM0_GPIO_IS_GPIO
#define PAD_SM0_GPIO_IS_GPIO BALL_N12_IS_GPIO
#endif 

#define BALL_M11 PAD_SM0_PCT
#define PAD_SM0_PCT 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_M11_IS_GPIO
#define BALL_M11_IS_GPIO 0
#endif 
#ifndef PAD_SM0_PCT_IS_GPIO
#define PAD_SM0_PCT_IS_GPIO BALL_M11_IS_GPIO
#endif 

#define BALL_R9 PAD_EJ_TCK
#define PAD_EJ_TCK 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_R9_IS_GPIO
#define BALL_R9_IS_GPIO 0
#endif 
#ifndef PAD_EJ_TCK_IS_GPIO
#define PAD_EJ_TCK_IS_GPIO BALL_R9_IS_GPIO
#endif 

#define BALL_P10 PAD_EJ_TMS
#define PAD_EJ_TMS 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_P10_IS_GPIO
#define BALL_P10_IS_GPIO 0
#endif 
#ifndef PAD_EJ_TMS_IS_GPIO
#define PAD_EJ_TMS_IS_GPIO BALL_P10_IS_GPIO
#endif 

#define BALL_R10 PAD_EJ_TDO
#define PAD_EJ_TDO 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_R10_IS_GPIO
#define BALL_R10_IS_GPIO 0
#endif 
#ifndef PAD_EJ_TDO_IS_GPIO
#define PAD_EJ_TDO_IS_GPIO BALL_R10_IS_GPIO
#endif 

#define BALL_N10 PAD_EJ_TDI
#define PAD_EJ_TDI 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_N10_IS_GPIO
#define BALL_N10_IS_GPIO 0
#endif 
#ifndef PAD_EJ_TDI_IS_GPIO
#define PAD_EJ_TDI_IS_GPIO BALL_N10_IS_GPIO
#endif 

#define BALL_M15 PAD_TS1_SYNC
#define PAD_TS1_SYNC 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_M15_IS_GPIO
#define BALL_M15_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_M15_IS_GPIO
#endif 

#define BALL_L13 PAD_TS1_VLD
#define PAD_TS1_VLD 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_L13_IS_GPIO
#define BALL_L13_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_L13_IS_GPIO
#endif 

#define BALL_M14 PAD_TS1_D0
#define PAD_TS1_D0 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_M14_IS_GPIO
#define BALL_M14_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_M14_IS_GPIO
#endif 

#define BALL_M13 PAD_TS1_D1
#define PAD_TS1_D1 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_M13_IS_GPIO
#define BALL_M13_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_M13_IS_GPIO
#endif 

#define BALL_N14 PAD_TS1_D2
#define PAD_TS1_D2 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_N14_IS_GPIO
#define BALL_N14_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_N14_IS_GPIO
#endif 

#define BALL_E15 PAD_TS1_D3
#define PAD_TS1_D3 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_E15_IS_GPIO
#define BALL_E15_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_E15_IS_GPIO
#endif 

#define BALL_E14 PAD_TS1_D4
#define PAD_TS1_D4 92
#define GPIO_PAD_92 GPIO91
#ifndef BALL_E14_IS_GPIO
#define BALL_E14_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_E14_IS_GPIO
#endif 

#define BALL_F15 PAD_TS1_D5
#define PAD_TS1_D5 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_F15_IS_GPIO
#define BALL_F15_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_F15_IS_GPIO
#endif 

#define BALL_F14 PAD_TS1_D6
#define PAD_TS1_D6 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_F14_IS_GPIO
#define BALL_F14_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_F14_IS_GPIO
#endif 

#define BALL_F13 PAD_TS1_D7
#define PAD_TS1_D7 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_F13_IS_GPIO
#define BALL_F13_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_F13_IS_GPIO
#endif 

#define BALL_L15 PAD_TS1_CLK
#define PAD_TS1_CLK 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_L15_IS_GPIO
#define BALL_L15_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_L15_IS_GPIO
#endif 

#define BALL_G14 PAD_TS0_SYNC
#define PAD_TS0_SYNC 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_G14_IS_GPIO
#define BALL_G14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_G14_IS_GPIO
#endif 

#define BALL_J15 PAD_TS0_VLD
#define PAD_TS0_VLD 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_J15_IS_GPIO
#define BALL_J15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_J15_IS_GPIO
#endif 

#define BALL_G13 PAD_TS0_D0
#define PAD_TS0_D0 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_G13_IS_GPIO
#define BALL_G13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_G13_IS_GPIO
#endif 

#define BALL_H14 PAD_TS0_D1
#define PAD_TS0_D1 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_H14_IS_GPIO
#define BALL_H14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_H14_IS_GPIO
#endif 

#define BALL_H15 PAD_TS0_D2
#define PAD_TS0_D2 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_H15_IS_GPIO
#define BALL_H15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_H15_IS_GPIO
#endif 

#define BALL_H13 PAD_TS0_D3
#define PAD_TS0_D3 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_H13_IS_GPIO
#define BALL_H13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_H13_IS_GPIO
#endif 

#define BALL_J14 PAD_TS0_D4
#define PAD_TS0_D4 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_J14_IS_GPIO
#define BALL_J14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_J14_IS_GPIO
#endif 

#define BALL_K14 PAD_TS0_D5
#define PAD_TS0_D5 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_K14_IS_GPIO
#define BALL_K14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_K14_IS_GPIO
#endif 

#define BALL_K13 PAD_TS0_D6
#define PAD_TS0_D6 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_K13_IS_GPIO
#define BALL_K13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_K13_IS_GPIO
#endif 

#define BALL_L14 PAD_TS0_D7
#define PAD_TS0_D7 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_L14_IS_GPIO
#define BALL_L14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_L14_IS_GPIO
#endif 

#define BALL_J13 PAD_TS0_CLK
#define PAD_TS0_CLK 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_J13_IS_GPIO
#define BALL_J13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_J13_IS_GPIO
#endif 

#define BALL_B12 PAD_CI_REGZ
#define PAD_CI_REGZ 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_B12_IS_GPIO
#define BALL_B12_IS_GPIO 0
#endif 
#ifndef PAD_CI_REGZ_IS_GPIO
#define PAD_CI_REGZ_IS_GPIO BALL_B12_IS_GPIO
#endif 

#define BALL_C10 PAD_CI_RST
#define PAD_CI_RST 69
#define GPIO_PAD_69 GPIO68
#ifndef BALL_C10_IS_GPIO
#define BALL_C10_IS_GPIO 0
#endif 
#ifndef PAD_CI_RST_IS_GPIO
#define PAD_CI_RST_IS_GPIO BALL_C10_IS_GPIO
#endif 

#define BALL_A8 PAD_CI_IOWRZ
#define PAD_CI_IOWRZ 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_A8_IS_GPIO
#define BALL_A8_IS_GPIO 0
#endif 
#ifndef PAD_CI_IOWRZ_IS_GPIO
#define PAD_CI_IOWRZ_IS_GPIO BALL_A8_IS_GPIO
#endif 

#define BALL_A7 PAD_CI_IORDZ
#define PAD_CI_IORDZ 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_A7_IS_GPIO
#define BALL_A7_IS_GPIO 0
#endif 
#ifndef PAD_CI_IORDZ_IS_GPIO
#define PAD_CI_IORDZ_IS_GPIO BALL_A7_IS_GPIO
#endif 

#define BALL_A14 PAD_CI_D2
#define PAD_CI_D2 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_A14_IS_GPIO
#define BALL_A14_IS_GPIO 0
#endif 
#ifndef PAD_CI_D2_IS_GPIO
#define PAD_CI_D2_IS_GPIO BALL_A14_IS_GPIO
#endif 

#define BALL_C13 PAD_CI_D1
#define PAD_CI_D1 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_C13_IS_GPIO
#define BALL_C13_IS_GPIO 0
#endif 
#ifndef PAD_CI_D1_IS_GPIO
#define PAD_CI_D1_IS_GPIO BALL_C13_IS_GPIO
#endif 

#define BALL_A13 PAD_CI_D0
#define PAD_CI_D0 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_A13_IS_GPIO
#define BALL_A13_IS_GPIO 0
#endif 
#ifndef PAD_CI_D0_IS_GPIO
#define PAD_CI_D0_IS_GPIO BALL_A13_IS_GPIO
#endif 

#define BALL_B13 PAD_CI_A0
#define PAD_CI_A0 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_B13_IS_GPIO
#define BALL_B13_IS_GPIO 0
#endif 
#ifndef PAD_CI_A0_IS_GPIO
#define PAD_CI_A0_IS_GPIO BALL_B13_IS_GPIO
#endif 

#define BALL_C12 PAD_CI_A1
#define PAD_CI_A1 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_C12_IS_GPIO
#define BALL_C12_IS_GPIO 0
#endif 
#ifndef PAD_CI_A1_IS_GPIO
#define PAD_CI_A1_IS_GPIO BALL_C12_IS_GPIO
#endif 

#define BALL_C11 PAD_CI_A2
#define PAD_CI_A2 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_C11_IS_GPIO
#define BALL_C11_IS_GPIO 0
#endif 
#ifndef PAD_CI_A2_IS_GPIO
#define PAD_CI_A2_IS_GPIO BALL_C11_IS_GPIO
#endif 

#define BALL_B11 PAD_CI_A3
#define PAD_CI_A3 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_B11_IS_GPIO
#define BALL_B11_IS_GPIO 0
#endif 
#ifndef PAD_CI_A3_IS_GPIO
#define PAD_CI_A3_IS_GPIO BALL_B11_IS_GPIO
#endif 

#define BALL_A11 PAD_CI_A4
#define PAD_CI_A4 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_A11_IS_GPIO
#define BALL_A11_IS_GPIO 0
#endif 
#ifndef PAD_CI_A4_IS_GPIO
#define PAD_CI_A4_IS_GPIO BALL_A11_IS_GPIO
#endif 

#define BALL_A10 PAD_CI_A5
#define PAD_CI_A5 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_A10_IS_GPIO
#define BALL_A10_IS_GPIO 0
#endif 
#ifndef PAD_CI_A5_IS_GPIO
#define PAD_CI_A5_IS_GPIO BALL_A10_IS_GPIO
#endif 

#define BALL_B10 PAD_CI_A6
#define PAD_CI_A6 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_B10_IS_GPIO
#define BALL_B10_IS_GPIO 0
#endif 
#ifndef PAD_CI_A6_IS_GPIO
#define PAD_CI_A6_IS_GPIO BALL_B10_IS_GPIO
#endif 

#define BALL_C9 PAD_CI_A7
#define PAD_CI_A7 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_C9_IS_GPIO
#define BALL_C9_IS_GPIO 0
#endif 
#ifndef PAD_CI_A7_IS_GPIO
#define PAD_CI_A7_IS_GPIO BALL_C9_IS_GPIO
#endif 

#define BALL_B9 PAD_CI_IRQAZ
#define PAD_CI_IRQAZ 68
#define GPIO_PAD_68 GPIO67
#ifndef BALL_B9_IS_GPIO
#define BALL_B9_IS_GPIO 0
#endif 
#ifndef PAD_CI_IRQAZ_IS_GPIO
#define PAD_CI_IRQAZ_IS_GPIO BALL_B9_IS_GPIO
#endif 

#define BALL_C8 PAD_CI_WEZ
#define PAD_CI_WEZ 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_C8_IS_GPIO
#define BALL_C8_IS_GPIO 0
#endif 
#ifndef PAD_CI_WEZ_IS_GPIO
#define PAD_CI_WEZ_IS_GPIO BALL_C8_IS_GPIO
#endif 

#define BALL_B8 PAD_CI_A8
#define PAD_CI_A8 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_B8_IS_GPIO
#define BALL_B8_IS_GPIO 0
#endif 
#ifndef PAD_CI_A8_IS_GPIO
#define PAD_CI_A8_IS_GPIO BALL_B8_IS_GPIO
#endif 

#define BALL_C7 PAD_CI_A9
#define PAD_CI_A9 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_C7_IS_GPIO
#define BALL_C7_IS_GPIO 0
#endif 
#ifndef PAD_CI_A9_IS_GPIO
#define PAD_CI_A9_IS_GPIO BALL_C7_IS_GPIO
#endif 

#define BALL_B7 PAD_CI_A11
#define PAD_CI_A11 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_B7_IS_GPIO
#define BALL_B7_IS_GPIO 0
#endif 
#ifndef PAD_CI_A11_IS_GPIO
#define PAD_CI_A11_IS_GPIO BALL_B7_IS_GPIO
#endif 

#define BALL_C6 PAD_CI_OEZ
#define PAD_CI_OEZ 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_C6_IS_GPIO
#define BALL_C6_IS_GPIO 0
#endif 
#ifndef PAD_CI_OEZ_IS_GPIO
#define PAD_CI_OEZ_IS_GPIO BALL_C6_IS_GPIO
#endif 

#define BALL_B6 PAD_CI_A10
#define PAD_CI_A10 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_B6_IS_GPIO
#define BALL_B6_IS_GPIO 0
#endif 
#ifndef PAD_CI_A10_IS_GPIO
#define PAD_CI_A10_IS_GPIO BALL_B6_IS_GPIO
#endif 

#define BALL_C5 PAD_CI_CEZ
#define PAD_CI_CEZ 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_C5_IS_GPIO
#define BALL_C5_IS_GPIO 0
#endif 
#ifndef PAD_CI_CEZ_IS_GPIO
#define PAD_CI_CEZ_IS_GPIO BALL_C5_IS_GPIO
#endif 

#define BALL_B5 PAD_CI_D7
#define PAD_CI_D7 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_B5_IS_GPIO
#define BALL_B5_IS_GPIO 0
#endif 
#ifndef PAD_CI_D7_IS_GPIO
#define PAD_CI_D7_IS_GPIO BALL_B5_IS_GPIO
#endif 

#define BALL_A5 PAD_CI_D6
#define PAD_CI_D6 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_A5_IS_GPIO
#define BALL_A5_IS_GPIO 0
#endif 
#ifndef PAD_CI_D6_IS_GPIO
#define PAD_CI_D6_IS_GPIO BALL_A5_IS_GPIO
#endif 

#define BALL_C4 PAD_CI_D5
#define PAD_CI_D5 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_C4_IS_GPIO
#define BALL_C4_IS_GPIO 0
#endif 
#ifndef PAD_CI_D5_IS_GPIO
#define PAD_CI_D5_IS_GPIO BALL_C4_IS_GPIO
#endif 

#define BALL_A4 PAD_CI_D4
#define PAD_CI_D4 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_A4_IS_GPIO
#define BALL_A4_IS_GPIO 0
#endif 
#ifndef PAD_CI_D4_IS_GPIO
#define PAD_CI_D4_IS_GPIO BALL_A4_IS_GPIO
#endif 

#define BALL_B4 PAD_CI_D3
#define PAD_CI_D3 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_B4_IS_GPIO
#define BALL_B4_IS_GPIO 0
#endif 
#ifndef PAD_CI_D3_IS_GPIO
#define PAD_CI_D3_IS_GPIO BALL_B4_IS_GPIO
#endif 

#define BALL_E9 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_E9_IS_GPIO
#define BALL_E9_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_E9_IS_GPIO
#endif 

#define BALL_C3 PAD_PHY_LED_LINK
#define PAD_PHY_LED_LINK 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_C3_IS_GPIO
#define BALL_C3_IS_GPIO 0
#endif 
#ifndef PAD_PHY_LED_LINK_IS_GPIO
#define PAD_PHY_LED_LINK_IS_GPIO BALL_C3_IS_GPIO
#endif 

#define BALL_B3 PAD_PHY_LED_DATA
#define PAD_PHY_LED_DATA 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_B3_IS_GPIO
#define BALL_B3_IS_GPIO 0
#endif 
#ifndef PAD_PHY_LED_DATA_IS_GPIO
#define PAD_PHY_LED_DATA_IS_GPIO BALL_B3_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0 
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1 
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1 
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 
#define CHIP_HAS_UART2_MODE2       1 
#define CHIP_HAS_UART2_MODE3       1 
#define CHIP_HAS_RGB_A             1 
#define CHIP_HAS_RGB_B             1 
#define CHIP_HAS_RGB_C             1 
#define CHIP_HAS_HDMI_A            1 
#define CHIP_HAS_HDMI_B            1 
#define CHIP_HAS_HDMI_C            1 
#define CHIP_HAS_SPI_CZ1           1 
#define CHIP_HAS_SPI_CZ2           0 
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 
#define CHIP_HAS_DDCR2             1 
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1 
#define CHIP_HAS_ET_MODE0_RMII     1 
#define CHIP_HAS_ET_MODE1_MII      1 
#define CHIP_HAS_ET_MODE1_RMII     1 
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1 
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0 
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7J

#endif /* _MSD7R134D_H_*/
