////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSD7C137D_H_
#define _MSD7C137D_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_D2 PAD_SAR_GPIO0
#define PAD_SAR_GPIO0 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_D2_IS_GPIO
#define BALL_D2_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO0_IS_GPIO
#define PAD_SAR_GPIO0_IS_GPIO BALL_D2_IS_GPIO
#endif 

#define BALL_D3 PAD_SAR_GPIO1
#define PAD_SAR_GPIO1 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_D3_IS_GPIO
#define BALL_D3_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO1_IS_GPIO
#define PAD_SAR_GPIO1_IS_GPIO BALL_D3_IS_GPIO
#endif 

#define BALL_D4 PAD_SAR_GPIO2
#define PAD_SAR_GPIO2 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO2_IS_GPIO
#define PAD_SAR_GPIO2_IS_GPIO BALL_D4_IS_GPIO
#endif 

#define BALL_E5 PAD_VPLUG_DET
#define PAD_VPLUG_DET 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_VPLUG_DET_IS_GPIO
#define PAD_VPLUG_DET_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define BALL_M3 PAD_PM_GPIO2
#define PAD_PM_GPIO2 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_M3_IS_GPIO
#define BALL_M3_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO2_IS_GPIO
#define PAD_PM_GPIO2_IS_GPIO BALL_M3_IS_GPIO
#endif 

#define BALL_P1 PAD_PM_GPIO3
#define PAD_PM_GPIO3 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_P1_IS_GPIO
#define BALL_P1_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO3_IS_GPIO
#define PAD_PM_GPIO3_IS_GPIO BALL_P1_IS_GPIO
#endif 

#define BALL_F4 PAD_PM_GPIO5
#define PAD_PM_GPIO5 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_F4_IS_GPIO
#define BALL_F4_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO5_IS_GPIO
#define PAD_PM_GPIO5_IS_GPIO BALL_F4_IS_GPIO
#endif 

#define BALL_E3 PAD_PM_GPIO6
#define PAD_PM_GPIO6 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_E3_IS_GPIO
#define BALL_E3_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO6_IS_GPIO
#define PAD_PM_GPIO6_IS_GPIO BALL_E3_IS_GPIO
#endif 

#define BALL_N2 PAD_PM_GPIO7
#define PAD_PM_GPIO7 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_N2_IS_GPIO
#define BALL_N2_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO7_IS_GPIO
#define PAD_PM_GPIO7_IS_GPIO BALL_N2_IS_GPIO
#endif 

#define BALL_K4 PAD_PM_GPIO9
#define PAD_PM_GPIO9 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_K4_IS_GPIO
#define BALL_K4_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO9_IS_GPIO
#define PAD_PM_GPIO9_IS_GPIO BALL_K4_IS_GPIO
#endif 

#define BALL_J4 PAD_PM_GPIO10
#define PAD_PM_GPIO10 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_J4_IS_GPIO
#define BALL_J4_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO10_IS_GPIO
#define PAD_PM_GPIO10_IS_GPIO BALL_J4_IS_GPIO
#endif 

#define BALL_L3 PAD_PM_GPIO12
#define PAD_PM_GPIO12 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_L3_IS_GPIO
#define BALL_L3_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO12_IS_GPIO
#define PAD_PM_GPIO12_IS_GPIO BALL_L3_IS_GPIO
#endif 

#define BALL_L4 PAD_PM_GPIO13
#define PAD_PM_GPIO13 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_L4_IS_GPIO
#define BALL_L4_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO13_IS_GPIO
#define PAD_PM_GPIO13_IS_GPIO BALL_L4_IS_GPIO
#endif 

#define BALL_F2 PAD_PM_GPIO0
#define PAD_PM_GPIO0 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_F2_IS_GPIO
#define BALL_F2_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO0_IS_GPIO
#define PAD_PM_GPIO0_IS_GPIO BALL_F2_IS_GPIO
#endif 

#define BALL_E2 PAD_PM_GPIO1
#define PAD_PM_GPIO1 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_E2_IS_GPIO
#define BALL_E2_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO1_IS_GPIO
#define PAD_PM_GPIO1_IS_GPIO BALL_E2_IS_GPIO
#endif 

#define BALL_E4 PAD_PM_GPIO4
#define PAD_PM_GPIO4 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO4_IS_GPIO
#define PAD_PM_GPIO4_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define BALL_D1 PAD_PM_IRIN
#define PAD_PM_IRIN 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_D1_IS_GPIO
#define BALL_D1_IS_GPIO 0
#endif 
#ifndef PAD_PM_IRIN_IS_GPIO
#define PAD_PM_IRIN_IS_GPIO BALL_D1_IS_GPIO
#endif 

#define BALL_C3 PAD_PM_SPI_RSTZ
#define PAD_PM_SPI_RSTZ 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_C3_IS_GPIO
#define BALL_C3_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_RSTZ_IS_GPIO
#define PAD_PM_SPI_RSTZ_IS_GPIO BALL_C3_IS_GPIO
#endif 

#define BALL_C1 PAD_PM_SPI_WPZ
#define PAD_PM_SPI_WPZ 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_C1_IS_GPIO
#define BALL_C1_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_WPZ_IS_GPIO
#define PAD_PM_SPI_WPZ_IS_GPIO BALL_C1_IS_GPIO
#endif 

#define BALL_B3 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_B3_IS_GPIO
#define BALL_B3_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_B3_IS_GPIO
#endif 

#define BALL_A2 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_A2_IS_GPIO
#define BALL_A2_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_A2_IS_GPIO
#endif 

#define BALL_E1 PAD_PM_GPIO14
#define PAD_PM_GPIO14 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_E1_IS_GPIO
#define BALL_E1_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO14_IS_GPIO
#define PAD_PM_GPIO14_IS_GPIO BALL_E1_IS_GPIO
#endif 

#define BALL_C2 PAD_PM_SPI_HOLDZ
#define PAD_PM_SPI_HOLDZ 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_C2_IS_GPIO
#define BALL_C2_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_HOLDZ_IS_GPIO
#define PAD_PM_SPI_HOLDZ_IS_GPIO BALL_C2_IS_GPIO
#endif 

#define BALL_B2 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_B2_IS_GPIO
#endif 

#define BALL_B1 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_B1_IS_GPIO
#define BALL_B1_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_B1_IS_GPIO
#endif 

#define BALL_F3 PAD_GPIO2
#define PAD_GPIO2 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_F3_IS_GPIO
#define BALL_F3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_F3_IS_GPIO
#endif 

#define BALL_K2 PAD_GPIO3
#define PAD_GPIO3 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_K2_IS_GPIO
#define BALL_K2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_K2_IS_GPIO
#endif 

#define BALL_L2 PAD_GPIO4
#define PAD_GPIO4 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_L2_IS_GPIO
#define BALL_L2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_L2_IS_GPIO
#endif 

#define BALL_L1 PAD_GPIO5
#define PAD_GPIO5 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_L1_IS_GPIO
#define BALL_L1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO BALL_L1_IS_GPIO
#endif 

#define BALL_K1 PAD_GPIO6
#define PAD_GPIO6 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_K1_IS_GPIO
#define BALL_K1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO BALL_K1_IS_GPIO
#endif 

#define BALL_M1 PAD_GPIO7
#define PAD_GPIO7 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_M1_IS_GPIO
#define BALL_M1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO BALL_M1_IS_GPIO
#endif 

#define BALL_K3 PAD_GPIO8
#define PAD_GPIO8 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_K3_IS_GPIO
#define BALL_K3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO BALL_K3_IS_GPIO
#endif 

#define BALL_J3 PAD_GPIO9
#define PAD_GPIO9 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_J3_IS_GPIO
#define BALL_J3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO BALL_J3_IS_GPIO
#endif 

#define BALL_H3 PAD_GPIO10
#define PAD_GPIO10 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_H3_IS_GPIO
#define BALL_H3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO BALL_H3_IS_GPIO
#endif 

#define BALL_J2 PAD_GPIO11
#define PAD_GPIO11 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_J2_IS_GPIO
#define BALL_J2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO BALL_J2_IS_GPIO
#endif 

#define BALL_H2 PAD_GPIO12
#define PAD_GPIO12 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_H2_IS_GPIO
#define BALL_H2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO BALL_H2_IS_GPIO
#endif 

#define BALL_H1 PAD_GPIO13
#define PAD_GPIO13 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_H1_IS_GPIO
#define BALL_H1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO BALL_H1_IS_GPIO
#endif 

#define BALL_G3 PAD_GPIO14
#define PAD_GPIO14 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_G3_IS_GPIO
#define BALL_G3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO BALL_G3_IS_GPIO
#endif 

#define BALL_G1 PAD_GPIO15
#define PAD_GPIO15 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_G1_IS_GPIO
#define BALL_G1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO BALL_G1_IS_GPIO
#endif 

#define BALL_G2 PAD_GPIO16
#define PAD_GPIO16 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_G2_IS_GPIO
#define BALL_G2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO BALL_G2_IS_GPIO
#endif 

#define BALL_H4 PAD_TM_GPIO0
#define PAD_TM_GPIO0 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_H4_IS_GPIO
#define BALL_H4_IS_GPIO 0
#endif 
#ifndef PAD_TM_GPIO0_IS_GPIO
#define PAD_TM_GPIO0_IS_GPIO BALL_H4_IS_GPIO
#endif 

#define BALL_G4 PAD_TM_GPIO1
#define PAD_TM_GPIO1 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_G4_IS_GPIO
#define BALL_G4_IS_GPIO 0
#endif 
#ifndef PAD_TM_GPIO1_IS_GPIO
#define PAD_TM_GPIO1_IS_GPIO BALL_G4_IS_GPIO
#endif 

#define BALL_T12 PAD_SM0_CLK
#define PAD_SM0_CLK 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_T12_IS_GPIO
#define BALL_T12_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CLK_IS_GPIO
#define PAD_SM0_CLK_IS_GPIO BALL_T12_IS_GPIO
#endif 

#define BALL_P14 PAD_SM0_RST
#define PAD_SM0_RST 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_P14_IS_GPIO
#define BALL_P14_IS_GPIO 0
#endif 
#ifndef PAD_SM0_RST_IS_GPIO
#define PAD_SM0_RST_IS_GPIO BALL_P14_IS_GPIO
#endif 

#define BALL_R15 PAD_SM0_C4
#define PAD_SM0_C4 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_R15_IS_GPIO
#define BALL_R15_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C4_IS_GPIO
#define PAD_SM0_C4_IS_GPIO BALL_R15_IS_GPIO
#endif 

#define BALL_P13 PAD_SM0_IO
#define PAD_SM0_IO 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_P13_IS_GPIO
#define BALL_P13_IS_GPIO 0
#endif 
#ifndef PAD_SM0_IO_IS_GPIO
#define PAD_SM0_IO_IS_GPIO BALL_P13_IS_GPIO
#endif 

#define BALL_T15 PAD_SM0_C8
#define PAD_SM0_C8 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_T15_IS_GPIO
#define BALL_T15_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C8_IS_GPIO
#define PAD_SM0_C8_IS_GPIO BALL_T15_IS_GPIO
#endif 

#define BALL_R14 PAD_SM0_CD
#define PAD_SM0_CD 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_R14_IS_GPIO
#define BALL_R14_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CD_IS_GPIO
#define PAD_SM0_CD_IS_GPIO BALL_R14_IS_GPIO
#endif 

#define BALL_T14 PAD_SM0_GPIO
#define PAD_SM0_GPIO 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_T14_IS_GPIO
#define BALL_T14_IS_GPIO 0
#endif 
#ifndef PAD_SM0_GPIO_IS_GPIO
#define PAD_SM0_GPIO_IS_GPIO BALL_T14_IS_GPIO
#endif 

#define BALL_P12 PAD_SM0_PCT
#define PAD_SM0_PCT 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_P12_IS_GPIO
#define BALL_P12_IS_GPIO 0
#endif 
#ifndef PAD_SM0_PCT_IS_GPIO
#define PAD_SM0_PCT_IS_GPIO BALL_P12_IS_GPIO
#endif 

#define BALL_N13 PAD_EJ_TCK
#define PAD_EJ_TCK 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_N13_IS_GPIO
#define BALL_N13_IS_GPIO 0
#endif 
#ifndef PAD_EJ_TCK_IS_GPIO
#define PAD_EJ_TCK_IS_GPIO BALL_N13_IS_GPIO
#endif 

#define BALL_M12 PAD_EJ_TMS
#define PAD_EJ_TMS 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_M12_IS_GPIO
#define BALL_M12_IS_GPIO 0
#endif 
#ifndef PAD_EJ_TMS_IS_GPIO
#define PAD_EJ_TMS_IS_GPIO BALL_M12_IS_GPIO
#endif 

#define BALL_N11 PAD_EJ_TDO
#define PAD_EJ_TDO 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_N11_IS_GPIO
#define BALL_N11_IS_GPIO 0
#endif 
#ifndef PAD_EJ_TDO_IS_GPIO
#define PAD_EJ_TDO_IS_GPIO BALL_N11_IS_GPIO
#endif 

#define BALL_L12 PAD_EJ_TDI
#define PAD_EJ_TDI 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_L12_IS_GPIO
#define BALL_L12_IS_GPIO 0
#endif 
#ifndef PAD_EJ_TDI_IS_GPIO
#define PAD_EJ_TDI_IS_GPIO BALL_L12_IS_GPIO
#endif 

#define BALL_L16 PAD_TS1_SYNC
#define PAD_TS1_SYNC 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_L16_IS_GPIO
#define BALL_L16_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_L16_IS_GPIO
#endif 

#define BALL_K14 PAD_TS1_VLD
#define PAD_TS1_VLD 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_K14_IS_GPIO
#define BALL_K14_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_K14_IS_GPIO
#endif 

#define BALL_L15 PAD_TS1_D0
#define PAD_TS1_D0 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_L15_IS_GPIO
#define BALL_L15_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_L15_IS_GPIO
#endif 

#define BALL_K16 PAD_TS1_CLK
#define PAD_TS1_CLK 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_K16_IS_GPIO
#define BALL_K16_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_K16_IS_GPIO
#endif 

#define BALL_R16 PAD_TS0_SYNC
#define PAD_TS0_SYNC 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_R16_IS_GPIO
#define BALL_R16_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_R16_IS_GPIO
#endif 

#define BALL_L13 PAD_TS0_VLD
#define PAD_TS0_VLD 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_L13_IS_GPIO
#define BALL_L13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_L13_IS_GPIO
#endif 

#define BALL_L14 PAD_TS0_D0
#define PAD_TS0_D0 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_L14_IS_GPIO
#define BALL_L14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_L14_IS_GPIO
#endif 

#define BALL_M15 PAD_TS0_D1
#define PAD_TS0_D1 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_M15_IS_GPIO
#define BALL_M15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_M15_IS_GPIO
#endif 

#define BALL_M14 PAD_TS0_D2
#define PAD_TS0_D2 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_M14_IS_GPIO
#define BALL_M14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_M14_IS_GPIO
#endif 

#define BALL_N15 PAD_TS0_D3
#define PAD_TS0_D3 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_N15_IS_GPIO
#define BALL_N15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_N15_IS_GPIO
#endif 

#define BALL_N16 PAD_TS0_D4
#define PAD_TS0_D4 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_N16_IS_GPIO
#define BALL_N16_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_N16_IS_GPIO
#endif 

#define BALL_N14 PAD_TS0_D5
#define PAD_TS0_D5 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_N14_IS_GPIO
#define BALL_N14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_N14_IS_GPIO
#endif 

#define BALL_P16 PAD_TS0_D6
#define PAD_TS0_D6 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_P16_IS_GPIO
#define BALL_P16_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_P16_IS_GPIO
#endif 

#define BALL_P15 PAD_TS0_D7
#define PAD_TS0_D7 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_P15_IS_GPIO
#define BALL_P15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_P15_IS_GPIO
#endif 

#define BALL_M13 PAD_TS0_CLK
#define PAD_TS0_CLK 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_M13_IS_GPIO
#define BALL_M13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_M13_IS_GPIO
#endif 

#define BALL_E13 PAD_I2CM1_SDA
#define PAD_I2CM1_SDA 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_E13_IS_GPIO
#define BALL_E13_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SDA_IS_GPIO
#define PAD_I2CM1_SDA_IS_GPIO BALL_E13_IS_GPIO
#endif 

#define BALL_E14 PAD_I2CM1_SCL
#define PAD_I2CM1_SCL 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_E14_IS_GPIO
#define BALL_E14_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SCL_IS_GPIO
#define PAD_I2CM1_SCL_IS_GPIO BALL_E14_IS_GPIO
#endif 

#define BALL_J14 PAD_I2CM0_SCL
#define PAD_I2CM0_SCL 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_J14_IS_GPIO
#define BALL_J14_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SCL_IS_GPIO
#define PAD_I2CM0_SCL_IS_GPIO BALL_J14_IS_GPIO
#endif 

#define BALL_J15 PAD_I2CM0_SDA
#define PAD_I2CM0_SDA 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_J15_IS_GPIO
#define BALL_J15_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SDA_IS_GPIO
#define PAD_I2CM0_SDA_IS_GPIO BALL_J15_IS_GPIO
#endif 

#define BALL_D12 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_D12_IS_GPIO
#define BALL_D12_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_D12_IS_GPIO
#endif 

#define BALL_C11 PAD_PM_HDMI_HPD
#define PAD_PM_HDMI_HPD 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_C11_IS_GPIO
#define BALL_C11_IS_GPIO 0
#endif 
#ifndef PAD_PM_HDMI_HPD_IS_GPIO
#define PAD_PM_HDMI_HPD_IS_GPIO BALL_C11_IS_GPIO
#endif 

#define BALL_E9 PAD_PM_HDMI_CEC
#define PAD_PM_HDMI_CEC 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_E9_IS_GPIO
#define BALL_E9_IS_GPIO 0
#endif 
#ifndef PAD_PM_HDMI_CEC_IS_GPIO
#define PAD_PM_HDMI_CEC_IS_GPIO BALL_E9_IS_GPIO
#endif 

#define BALL_A6 PAD_PHY_LED_LINK
#define PAD_PHY_LED_LINK 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_A6_IS_GPIO
#define BALL_A6_IS_GPIO 0
#endif 
#ifndef PAD_PHY_LED_LINK_IS_GPIO
#define PAD_PHY_LED_LINK_IS_GPIO BALL_A6_IS_GPIO
#endif 

#define BALL_B6 PAD_PHY_LED_DATA
#define PAD_PHY_LED_DATA 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_B6_IS_GPIO
#define BALL_B6_IS_GPIO 0
#endif 
#ifndef PAD_PHY_LED_DATA_IS_GPIO
#define PAD_PHY_LED_DATA_IS_GPIO BALL_B6_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0 
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1 
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1 
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 
#define CHIP_HAS_UART2_MODE2       1 
#define CHIP_HAS_UART2_MODE3       1 
#define CHIP_HAS_RGB_A             1 
#define CHIP_HAS_RGB_B             1 
#define CHIP_HAS_RGB_C             1 
#define CHIP_HAS_HDMI_A            1 
#define CHIP_HAS_HDMI_B            1 
#define CHIP_HAS_HDMI_C            1 
#define CHIP_HAS_SPI_CZ1           1 
#define CHIP_HAS_SPI_CZ2           0 
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 
#define CHIP_HAS_DDCR2             1 
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1 
#define CHIP_HAS_ET_MODE0_RMII     1 
#define CHIP_HAS_ET_MODE1_MII      1 
#define CHIP_HAS_ET_MODE1_RMII     1 
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1 
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0 
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7J

#endif /* _MSD7C137D_H_*/
