////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSD7C127D_H_
#define _MSD7C127D_H_

#define PAD_NC 9999
#define PAD_GND 0

#define PIN_103 PAD_SAR_GPIO0
#define PAD_SAR_GPIO0 128
#define GPIO_PAD_128 GPIO127
#ifndef PIN_103_IS_GPIO
#define PIN_103_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO0_IS_GPIO
#define PAD_SAR_GPIO0_IS_GPIO PIN_103_IS_GPIO
#endif 

#define PIN_104 PAD_SAR_GPIO1
#define PAD_SAR_GPIO1 129
#define GPIO_PAD_129 GPIO128
#ifndef PIN_104_IS_GPIO
#define PIN_104_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO1_IS_GPIO
#define PAD_SAR_GPIO1_IS_GPIO PIN_104_IS_GPIO
#endif 

#define PIN_105 PAD_SAR_GPIO2
#define PAD_SAR_GPIO2 130
#define GPIO_PAD_130 GPIO129
#ifndef PIN_105_IS_GPIO
#define PIN_105_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO2_IS_GPIO
#define PAD_SAR_GPIO2_IS_GPIO PIN_105_IS_GPIO
#endif 

#define PIN_106 PAD_VPLUG_DET
#define PAD_VPLUG_DET 131
#define GPIO_PAD_131 GPIO130
#ifndef PIN_106_IS_GPIO
#define PIN_106_IS_GPIO 0
#endif 
#ifndef PAD_VPLUG_DET_IS_GPIO
#define PAD_VPLUG_DET_IS_GPIO PIN_106_IS_GPIO
#endif 

#define PAD_PM_GPIO2 9999
#ifndef PAD_PM_GPIO2_IS_GPIO
#define PAD_PM_GPIO2_IS_GPIO 0
#endif 

#define PAD_PM_GPIO3 9999
#ifndef PAD_PM_GPIO3_IS_GPIO
#define PAD_PM_GPIO3_IS_GPIO 0
#endif 

#define PAD_PM_GPIO5 9999
#ifndef PAD_PM_GPIO5_IS_GPIO
#define PAD_PM_GPIO5_IS_GPIO 0
#endif 

#define PAD_PM_GPIO6 9999
#ifndef PAD_PM_GPIO6_IS_GPIO
#define PAD_PM_GPIO6_IS_GPIO 0
#endif 

#define PAD_PM_GPIO7 9999
#ifndef PAD_PM_GPIO7_IS_GPIO
#define PAD_PM_GPIO7_IS_GPIO 0
#endif 

#define PIN_109 PAD_PM_GPIO9
#define PAD_PM_GPIO9 118
#define GPIO_PAD_118 GPIO117
#ifndef PIN_109_IS_GPIO
#define PIN_109_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO9_IS_GPIO
#define PAD_PM_GPIO9_IS_GPIO PIN_109_IS_GPIO
#endif 

#define PIN_111 PAD_PM_GPIO10
#define PAD_PM_GPIO10 119
#define GPIO_PAD_119 GPIO118
#ifndef PIN_111_IS_GPIO
#define PIN_111_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO10_IS_GPIO
#define PAD_PM_GPIO10_IS_GPIO PIN_111_IS_GPIO
#endif 

#define PIN_112 PAD_PM_GPIO12
#define PAD_PM_GPIO12 121
#define GPIO_PAD_121 GPIO120
#ifndef PIN_112_IS_GPIO
#define PIN_112_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO12_IS_GPIO
#define PAD_PM_GPIO12_IS_GPIO PIN_112_IS_GPIO
#endif 

#define PIN_113 PAD_PM_GPIO13
#define PAD_PM_GPIO13 122
#define GPIO_PAD_122 GPIO121
#ifndef PIN_113_IS_GPIO
#define PIN_113_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO13_IS_GPIO
#define PAD_PM_GPIO13_IS_GPIO PIN_113_IS_GPIO
#endif 

#define PIN_114 PAD_PM_GPIO0
#define PAD_PM_GPIO0 109
#define GPIO_PAD_109 GPIO108
#ifndef PIN_114_IS_GPIO
#define PIN_114_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO0_IS_GPIO
#define PAD_PM_GPIO0_IS_GPIO PIN_114_IS_GPIO
#endif 

#define PIN_115 PAD_PM_GPIO1
#define PAD_PM_GPIO1 110
#define GPIO_PAD_110 GPIO109
#ifndef PIN_115_IS_GPIO
#define PIN_115_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO1_IS_GPIO
#define PAD_PM_GPIO1_IS_GPIO PIN_115_IS_GPIO
#endif 

#define PIN_116 PAD_PM_GPIO4
#define PAD_PM_GPIO4 113
#define GPIO_PAD_113 GPIO112
#ifndef PIN_116_IS_GPIO
#define PIN_116_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO4_IS_GPIO
#define PAD_PM_GPIO4_IS_GPIO PIN_116_IS_GPIO
#endif 

#define PIN_121 PAD_PM_IRIN
#define PAD_PM_IRIN 101
#define GPIO_PAD_101 GPIO100
#ifndef PIN_121_IS_GPIO
#define PIN_121_IS_GPIO 0
#endif 
#ifndef PAD_PM_IRIN_IS_GPIO
#define PAD_PM_IRIN_IS_GPIO PIN_121_IS_GPIO
#endif 

#define PAD_PM_SPI_RSTZ 9999
#ifndef PAD_PM_SPI_RSTZ_IS_GPIO
#define PAD_PM_SPI_RSTZ_IS_GPIO 0
#endif 

#define PIN_122 PAD_PM_SPI_WPZ
#define PAD_PM_SPI_WPZ 106
#define GPIO_PAD_106 GPIO105
#ifndef PIN_122_IS_GPIO
#define PIN_122_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_WPZ_IS_GPIO
#define PAD_PM_SPI_WPZ_IS_GPIO PIN_122_IS_GPIO
#endif 

#define PIN_123 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 102
#define GPIO_PAD_102 GPIO101
#ifndef PIN_123_IS_GPIO
#define PIN_123_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO PIN_123_IS_GPIO
#endif 

#define PIN_124 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 105
#define GPIO_PAD_105 GPIO104
#ifndef PIN_124_IS_GPIO
#define PIN_124_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO PIN_124_IS_GPIO
#endif 

#define PIN_125 PAD_PM_GPIO14
#define PAD_PM_GPIO14 123
#define GPIO_PAD_123 GPIO122
#ifndef PIN_125_IS_GPIO
#define PIN_125_IS_GPIO 0
#endif 
#ifndef PAD_PM_GPIO14_IS_GPIO
#define PAD_PM_GPIO14_IS_GPIO PIN_125_IS_GPIO
#endif 

#define PIN_126 PAD_PM_SPI_HOLDZ
#define PAD_PM_SPI_HOLDZ 107
#define GPIO_PAD_107 GPIO106
#ifndef PIN_126_IS_GPIO
#define PIN_126_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_HOLDZ_IS_GPIO
#define PAD_PM_SPI_HOLDZ_IS_GPIO PIN_126_IS_GPIO
#endif 

#define PIN_127 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 103
#define GPIO_PAD_103 GPIO102
#ifndef PIN_127_IS_GPIO
#define PIN_127_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO PIN_127_IS_GPIO
#endif 

#define PIN_128 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 104
#define GPIO_PAD_104 GPIO103
#ifndef PIN_128_IS_GPIO
#define PIN_128_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO PIN_128_IS_GPIO
#endif 

#define PAD_GPIO2 9999
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO 0
#endif 

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif 

#define PAD_GPIO4 9999
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO 0
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif 

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif 

#define PIN_2 PAD_GPIO9
#define PAD_GPIO9 32
#define GPIO_PAD_32 GPIO31
#ifndef PIN_2_IS_GPIO
#define PIN_2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO PIN_2_IS_GPIO
#endif 

#define PIN_3 PAD_GPIO10
#define PAD_GPIO10 33
#define GPIO_PAD_33 GPIO32
#ifndef PIN_3_IS_GPIO
#define PIN_3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO PIN_3_IS_GPIO
#endif 

#define PIN_4 PAD_GPIO11
#define PAD_GPIO11 34
#define GPIO_PAD_34 GPIO33
#ifndef PIN_4_IS_GPIO
#define PIN_4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO PIN_4_IS_GPIO
#endif 

#define PIN_5 PAD_GPIO12
#define PAD_GPIO12 35
#define GPIO_PAD_35 GPIO34
#ifndef PIN_5_IS_GPIO
#define PIN_5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO PIN_5_IS_GPIO
#endif 

#define PIN_6 PAD_GPIO13
#define PAD_GPIO13 36
#define GPIO_PAD_36 GPIO35
#ifndef PIN_6_IS_GPIO
#define PIN_6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO PIN_6_IS_GPIO
#endif 

#define PIN_7 PAD_GPIO14
#define PAD_GPIO14 37
#define GPIO_PAD_37 GPIO36
#ifndef PIN_7_IS_GPIO
#define PIN_7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO PIN_7_IS_GPIO
#endif 

#define PIN_8 PAD_GPIO15
#define PAD_GPIO15 38
#define GPIO_PAD_38 GPIO37
#ifndef PIN_8_IS_GPIO
#define PIN_8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO PIN_8_IS_GPIO
#endif 

#define PIN_9 PAD_GPIO16
#define PAD_GPIO16 39
#define GPIO_PAD_39 GPIO38
#ifndef PIN_9_IS_GPIO
#define PIN_9_IS_GPIO 0
#endif 
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO PIN_9_IS_GPIO
#endif 

#define PIN_11 PAD_TM_GPIO0
#define PAD_TM_GPIO0 132
#define GPIO_PAD_132 GPIO131
#ifndef PIN_11_IS_GPIO
#define PIN_11_IS_GPIO 0
#endif 
#ifndef PAD_TM_GPIO0_IS_GPIO
#define PAD_TM_GPIO0_IS_GPIO PIN_11_IS_GPIO
#endif 

#define PIN_12 PAD_TM_GPIO1
#define PAD_TM_GPIO1 133
#define GPIO_PAD_133 GPIO132
#ifndef PIN_12_IS_GPIO
#define PIN_12_IS_GPIO 0
#endif 
#ifndef PAD_TM_GPIO1_IS_GPIO
#define PAD_TM_GPIO1_IS_GPIO PIN_12_IS_GPIO
#endif 

#define PIN_27 PAD_SM0_CLK
#define PAD_SM0_CLK 9
#define GPIO_PAD_9 GPIO8
#ifndef PIN_27_IS_GPIO
#define PIN_27_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CLK_IS_GPIO
#define PAD_SM0_CLK_IS_GPIO PIN_27_IS_GPIO
#endif 

#define PIN_28 PAD_SM0_RST
#define PAD_SM0_RST 10
#define GPIO_PAD_10 GPIO9
#ifndef PIN_28_IS_GPIO
#define PIN_28_IS_GPIO 0
#endif 
#ifndef PAD_SM0_RST_IS_GPIO
#define PAD_SM0_RST_IS_GPIO PIN_28_IS_GPIO
#endif 

#define PIN_29 PAD_SM0_C4
#define PAD_SM0_C4 11
#define GPIO_PAD_11 GPIO10
#ifndef PIN_29_IS_GPIO
#define PIN_29_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C4_IS_GPIO
#define PAD_SM0_C4_IS_GPIO PIN_29_IS_GPIO
#endif 

#define PIN_30 PAD_SM0_IO
#define PAD_SM0_IO 12
#define GPIO_PAD_12 GPIO11
#ifndef PIN_30_IS_GPIO
#define PIN_30_IS_GPIO 0
#endif 
#ifndef PAD_SM0_IO_IS_GPIO
#define PAD_SM0_IO_IS_GPIO PIN_30_IS_GPIO
#endif 

#define PIN_31 PAD_SM0_C8
#define PAD_SM0_C8 13
#define GPIO_PAD_13 GPIO12
#ifndef PIN_31_IS_GPIO
#define PIN_31_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C8_IS_GPIO
#define PAD_SM0_C8_IS_GPIO PIN_31_IS_GPIO
#endif 

#define PIN_33 PAD_SM0_CD
#define PAD_SM0_CD 14
#define GPIO_PAD_14 GPIO13
#ifndef PIN_33_IS_GPIO
#define PIN_33_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CD_IS_GPIO
#define PAD_SM0_CD_IS_GPIO PIN_33_IS_GPIO
#endif 

#define PIN_34 PAD_SM0_GPIO
#define PAD_SM0_GPIO 15
#define GPIO_PAD_15 GPIO14
#ifndef PIN_34_IS_GPIO
#define PIN_34_IS_GPIO 0
#endif 
#ifndef PAD_SM0_GPIO_IS_GPIO
#define PAD_SM0_GPIO_IS_GPIO PIN_34_IS_GPIO
#endif 

#define PIN_35 PAD_SM0_PCT
#define PAD_SM0_PCT 16
#define GPIO_PAD_16 GPIO15
#ifndef PIN_35_IS_GPIO
#define PIN_35_IS_GPIO 0
#endif 
#ifndef PAD_SM0_PCT_IS_GPIO
#define PAD_SM0_PCT_IS_GPIO PIN_35_IS_GPIO
#endif 

#define PAD_EJ_TCK 9999
#ifndef PAD_EJ_TCK_IS_GPIO
#define PAD_EJ_TCK_IS_GPIO 0
#endif 

#define PAD_EJ_TMS 9999
#ifndef PAD_EJ_TMS_IS_GPIO
#define PAD_EJ_TMS_IS_GPIO 0
#endif 

#define PAD_EJ_TDO 9999
#ifndef PAD_EJ_TDO_IS_GPIO
#define PAD_EJ_TDO_IS_GPIO 0
#endif 

#define PAD_EJ_TDI 9999
#ifndef PAD_EJ_TDI_IS_GPIO
#define PAD_EJ_TDI_IS_GPIO 0
#endif 

#define PIN_36 PAD_TS1_SYNC
#define PAD_TS1_SYNC 86
#define GPIO_PAD_86 GPIO85
#ifndef PIN_36_IS_GPIO
#define PIN_36_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO PIN_36_IS_GPIO
#endif 

#define PIN_37 PAD_TS1_VLD
#define PAD_TS1_VLD 87
#define GPIO_PAD_87 GPIO86
#ifndef PIN_37_IS_GPIO
#define PIN_37_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO PIN_37_IS_GPIO
#endif 

#define PIN_38 PAD_TS1_D0
#define PAD_TS1_D0 88
#define GPIO_PAD_88 GPIO87
#ifndef PIN_38_IS_GPIO
#define PIN_38_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO PIN_38_IS_GPIO
#endif 

#define PAD_TS1_D1 9999
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO 0
#endif 

#define PAD_TS1_D2 9999
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO 0
#endif 

#define PAD_TS1_D3 9999
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO 0
#endif 

#define PAD_TS1_D4 9999
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO 0
#endif 

#define PAD_TS1_D5 9999
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO 0
#endif 

#define PAD_TS1_D6 9999
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO 0
#endif 

#define PAD_TS1_D7 9999
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO 0
#endif 

#define PIN_40 PAD_TS1_CLK
#define PAD_TS1_CLK 96
#define GPIO_PAD_96 GPIO95
#ifndef PIN_40_IS_GPIO
#define PIN_40_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO PIN_40_IS_GPIO
#endif 

#define PIN_41 PAD_TS0_SYNC
#define PAD_TS0_SYNC 75
#define GPIO_PAD_75 GPIO74
#ifndef PIN_41_IS_GPIO
#define PIN_41_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO PIN_41_IS_GPIO
#endif 

#define PIN_42 PAD_TS0_VLD
#define PAD_TS0_VLD 76
#define GPIO_PAD_76 GPIO75
#ifndef PIN_42_IS_GPIO
#define PIN_42_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO PIN_42_IS_GPIO
#endif 

#define PIN_43 PAD_TS0_D0
#define PAD_TS0_D0 77
#define GPIO_PAD_77 GPIO76
#ifndef PIN_43_IS_GPIO
#define PIN_43_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO PIN_43_IS_GPIO
#endif 

#define PIN_44 PAD_TS0_D1
#define PAD_TS0_D1 78
#define GPIO_PAD_78 GPIO77
#ifndef PIN_44_IS_GPIO
#define PIN_44_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO PIN_44_IS_GPIO
#endif 

#define PIN_45 PAD_TS0_D2
#define PAD_TS0_D2 79
#define GPIO_PAD_79 GPIO78
#ifndef PIN_45_IS_GPIO
#define PIN_45_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO PIN_45_IS_GPIO
#endif 

#define PIN_46 PAD_TS0_D3
#define PAD_TS0_D3 80
#define GPIO_PAD_80 GPIO79
#ifndef PIN_46_IS_GPIO
#define PIN_46_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO PIN_46_IS_GPIO
#endif 

#define PIN_47 PAD_TS0_D4
#define PAD_TS0_D4 81
#define GPIO_PAD_81 GPIO80
#ifndef PIN_47_IS_GPIO
#define PIN_47_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO PIN_47_IS_GPIO
#endif 

#define PIN_49 PAD_TS0_D5
#define PAD_TS0_D5 82
#define GPIO_PAD_82 GPIO81
#ifndef PIN_49_IS_GPIO
#define PIN_49_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO PIN_49_IS_GPIO
#endif 

#define PIN_50 PAD_TS0_D6
#define PAD_TS0_D6 83
#define GPIO_PAD_83 GPIO82
#ifndef PIN_50_IS_GPIO
#define PIN_50_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO PIN_50_IS_GPIO
#endif 

#define PIN_51 PAD_TS0_D7
#define PAD_TS0_D7 84
#define GPIO_PAD_84 GPIO83
#ifndef PIN_51_IS_GPIO
#define PIN_51_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO PIN_51_IS_GPIO
#endif 

#define PIN_52 PAD_TS0_CLK
#define PAD_TS0_CLK 85
#define GPIO_PAD_85 GPIO84
#ifndef PIN_52_IS_GPIO
#define PIN_52_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO PIN_52_IS_GPIO
#endif 

#define PIN_53 PAD_I2CM1_SDA
#define PAD_I2CM1_SDA 100
#define GPIO_PAD_100 GPIO99
#ifndef PIN_53_IS_GPIO
#define PIN_53_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SDA_IS_GPIO
#define PAD_I2CM1_SDA_IS_GPIO PIN_53_IS_GPIO
#endif 

#define PIN_54 PAD_I2CM1_SCL
#define PAD_I2CM1_SCL 99
#define GPIO_PAD_99 GPIO98
#ifndef PIN_54_IS_GPIO
#define PIN_54_IS_GPIO 0
#endif 
#ifndef PAD_I2CM1_SCL_IS_GPIO
#define PAD_I2CM1_SCL_IS_GPIO PIN_54_IS_GPIO
#endif 

#define PIN_55 PAD_I2CM0_SCL
#define PAD_I2CM0_SCL 97
#define GPIO_PAD_97 GPIO96
#ifndef PIN_55_IS_GPIO
#define PIN_55_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SCL_IS_GPIO
#define PAD_I2CM0_SCL_IS_GPIO PIN_55_IS_GPIO
#endif 

#define PIN_56 PAD_I2CM0_SDA
#define PAD_I2CM0_SDA 98
#define GPIO_PAD_98 GPIO97
#ifndef PIN_56_IS_GPIO
#define PIN_56_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SDA_IS_GPIO
#define PAD_I2CM0_SDA_IS_GPIO PIN_56_IS_GPIO
#endif 

#define PAD_CI_REGZ 9999
#ifndef PAD_CI_REGZ_IS_GPIO
#define PAD_CI_REGZ_IS_GPIO 0
#endif 

#define PAD_CI_RST 9999
#ifndef PAD_CI_RST_IS_GPIO
#define PAD_CI_RST_IS_GPIO 0
#endif 

#define PAD_CI_IOWRZ 9999
#ifndef PAD_CI_IOWRZ_IS_GPIO
#define PAD_CI_IOWRZ_IS_GPIO 0
#endif 

#define PAD_CI_IORDZ 9999
#ifndef PAD_CI_IORDZ_IS_GPIO
#define PAD_CI_IORDZ_IS_GPIO 0
#endif 

#define PAD_CI_D2 9999
#ifndef PAD_CI_D2_IS_GPIO
#define PAD_CI_D2_IS_GPIO 0
#endif 

#define PAD_CI_D1 9999
#ifndef PAD_CI_D1_IS_GPIO
#define PAD_CI_D1_IS_GPIO 0
#endif 

#define PAD_CI_D0 9999
#ifndef PAD_CI_D0_IS_GPIO
#define PAD_CI_D0_IS_GPIO 0
#endif 

#define PAD_CI_A0 9999
#ifndef PAD_CI_A0_IS_GPIO
#define PAD_CI_A0_IS_GPIO 0
#endif 

#define PAD_CI_A1 9999
#ifndef PAD_CI_A1_IS_GPIO
#define PAD_CI_A1_IS_GPIO 0
#endif 

#define PAD_CI_A2 9999
#ifndef PAD_CI_A2_IS_GPIO
#define PAD_CI_A2_IS_GPIO 0
#endif 

#define PAD_CI_A3 9999
#ifndef PAD_CI_A3_IS_GPIO
#define PAD_CI_A3_IS_GPIO 0
#endif 

#define PAD_CI_A4 9999
#ifndef PAD_CI_A4_IS_GPIO
#define PAD_CI_A4_IS_GPIO 0
#endif 

#define PAD_CI_A5 9999
#ifndef PAD_CI_A5_IS_GPIO
#define PAD_CI_A5_IS_GPIO 0
#endif 

#define PAD_CI_A6 9999
#ifndef PAD_CI_A6_IS_GPIO
#define PAD_CI_A6_IS_GPIO 0
#endif 

#define PAD_CI_A7 9999
#ifndef PAD_CI_A7_IS_GPIO
#define PAD_CI_A7_IS_GPIO 0
#endif 

#define PAD_CI_IRQAZ 9999
#ifndef PAD_CI_IRQAZ_IS_GPIO
#define PAD_CI_IRQAZ_IS_GPIO 0
#endif 

#define PAD_CI_WEZ 9999
#ifndef PAD_CI_WEZ_IS_GPIO
#define PAD_CI_WEZ_IS_GPIO 0
#endif 

#define PAD_CI_A8 9999
#ifndef PAD_CI_A8_IS_GPIO
#define PAD_CI_A8_IS_GPIO 0
#endif 

#define PAD_CI_A9 9999
#ifndef PAD_CI_A9_IS_GPIO
#define PAD_CI_A9_IS_GPIO 0
#endif 

#define PAD_CI_A11 9999
#ifndef PAD_CI_A11_IS_GPIO
#define PAD_CI_A11_IS_GPIO 0
#endif 

#define PAD_CI_OEZ 9999
#ifndef PAD_CI_OEZ_IS_GPIO
#define PAD_CI_OEZ_IS_GPIO 0
#endif 

#define PAD_CI_A10 9999
#ifndef PAD_CI_A10_IS_GPIO
#define PAD_CI_A10_IS_GPIO 0
#endif 

#define PAD_CI_CEZ 9999
#ifndef PAD_CI_CEZ_IS_GPIO
#define PAD_CI_CEZ_IS_GPIO 0
#endif 

#define PAD_CI_D7 9999
#ifndef PAD_CI_D7_IS_GPIO
#define PAD_CI_D7_IS_GPIO 0
#endif 

#define PAD_CI_D6 9999
#ifndef PAD_CI_D6_IS_GPIO
#define PAD_CI_D6_IS_GPIO 0
#endif 

#define PAD_CI_D5 9999
#ifndef PAD_CI_D5_IS_GPIO
#define PAD_CI_D5_IS_GPIO 0
#endif 

#define PAD_CI_D4 9999
#ifndef PAD_CI_D4_IS_GPIO
#define PAD_CI_D4_IS_GPIO 0
#endif 

#define PAD_CI_D3 9999
#ifndef PAD_CI_D3_IS_GPIO
#define PAD_CI_D3_IS_GPIO 0
#endif 

#define PIN_79 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 1
#define GPIO_PAD_1 GPIO0
#ifndef PIN_79_IS_GPIO
#define PIN_79_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO PIN_79_IS_GPIO
#endif 

#define PIN_80 PAD_PM_HDMI_HPD
#define PAD_PM_HDMI_HPD 127
#define GPIO_PAD_127 GPIO126
#ifndef PIN_80_IS_GPIO
#define PIN_80_IS_GPIO 0
#endif 
#ifndef PAD_PM_HDMI_HPD_IS_GPIO
#define PAD_PM_HDMI_HPD_IS_GPIO PIN_80_IS_GPIO
#endif 

#define PIN_83 PAD_PM_HDMI_CEC
#define PAD_PM_HDMI_CEC 126
#define GPIO_PAD_126 GPIO125
#ifndef PIN_83_IS_GPIO
#define PIN_83_IS_GPIO 0
#endif 
#ifndef PAD_PM_HDMI_CEC_IS_GPIO
#define PAD_PM_HDMI_CEC_IS_GPIO PIN_83_IS_GPIO
#endif 

#define PIN_96 PAD_PHY_LED_LINK
#define PAD_PHY_LED_LINK 124
#define GPIO_PAD_124 GPIO123
#ifndef PIN_96_IS_GPIO
#define PIN_96_IS_GPIO 0
#endif 
#ifndef PAD_PHY_LED_LINK_IS_GPIO
#define PAD_PHY_LED_LINK_IS_GPIO PIN_96_IS_GPIO
#endif 

#define PIN_97 PAD_PHY_LED_DATA
#define PAD_PHY_LED_DATA 125
#define GPIO_PAD_125 GPIO124
#ifndef PIN_97_IS_GPIO
#define PIN_97_IS_GPIO 0
#endif 
#ifndef PAD_PHY_LED_DATA_IS_GPIO
#define PAD_PHY_LED_DATA_IS_GPIO PIN_97_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0 
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1 
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1 
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 
#define CHIP_HAS_UART2_MODE2       1 
#define CHIP_HAS_UART2_MODE3       1 
#define CHIP_HAS_RGB_A             1 
#define CHIP_HAS_RGB_B             1 
#define CHIP_HAS_RGB_C             1 
#define CHIP_HAS_HDMI_A            1 
#define CHIP_HAS_HDMI_B            1 
#define CHIP_HAS_HDMI_C            1 
#define CHIP_HAS_SPI_CZ1           1 
#define CHIP_HAS_SPI_CZ2           0 
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 
#define CHIP_HAS_DDCR2             1 
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1 
#define CHIP_HAS_ET_MODE0_RMII     1 
#define CHIP_HAS_ET_MODE1_MII      1 
#define CHIP_HAS_ET_MODE1_RMII     1 
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1 
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0 
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7J

#endif /* _MSD7C127D_H_*/
