#ifndef CYGONCE_PKGCONF_DEVS_ETH_MIPS_MIPS32_MALTA_H
#define CYGONCE_PKGCONF_DEVS_ETH_MIPS_MIPS32_MALTA_H
/*
 * File <pkgconf/devs_eth_mips_mips32_malta.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGINT_DEVS_ETH_AMD_PCNET_REQUIRED 1
#define CYGINT_DEVS_ETH_AMD_PCNET_REQUIRED_1
#define CYGINT_DEVS_ETH_MSTAR_GMAC_REQUIRED 1
#define CYGINT_DEVS_ETH_MSTAR_GMAC_REQUIRED_1
#define CYGINT_DEVS_ETH_MSTAR_EMAC_REQUIRED 1
#define CYGINT_DEVS_ETH_MSTAR_EMAC_REQUIRED_1
#define CYGPKG_DEVS_ETH_MIPS_MIPS32_MALTA_ETH0 1
#define CYGNUM_DEVS_ETH_MIPS_MIPS32_MALTA_ETH0_RX_RING_SIZE 4
#define CYGNUM_DEVS_ETH_MIPS_MIPS32_MALTA_ETH0_RX_RING_SIZE_4
#define CYGNUM_DEVS_ETH_MIPS_MIPS32_MALTA_ETH0_TX_RING_SIZE 16
#define CYGNUM_DEVS_ETH_MIPS_MIPS32_MALTA_ETH0_TX_RING_SIZE_16
#define CYGDAT_DEVS_ETH_MIPS_MIPS32_MALTA_ETH0_NAME "eth0"
#define CYGSEM_DEVS_ETH_MIPS_MIPS32_MALTA_ETH0_SET_ESA 1
#define CYGDAT_DEVS_ETH_MIPS_MIPS32_MALTA_ETH0_ESA {0x08, 0x88, 0x12, 0x34, 0x56, 0x78}

#endif
