#ifndef CYGONCE_PKGCONF_FS_JFFS2_H
#define CYGONCE_PKGCONF_FS_JFFS2_H
/*
 * File <pkgconf/fs_jffs2.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGOPT_FS_JFFS2_WRITE 1
#define CYGOPT_FS_JFFS2_COMPRESS 1
#define JFFS2_COMPRESSION 1
#define CYGOPT_FS_JFFS2_COMPRESS_ZLIB 1
#define CONFIG_JFFS2_ZLIB 1
#define CYGOPT_FS_JFFS2_COMPRESS_RTIME 1
#define CONFIG_JFFS2_RTIME 1
#define CYGOPT_FS_JFFS2_COMPRESS_CMODE PRIORITY
#define CYGOPT_FS_JFFS2_COMPRESS_CMODE_PRIORITY
#define CONFIG_JFFS2_CMODE PRIORITY
#define CONFIG_JFFS2_CMODE_PRIORITY
#define CYGNUM_FS_JFFS2_RAW_NODE_REF_CACHE_POOL_SIZE 0
#define CYGNUM_FS_JFFS2_RAW_NODE_REF_CACHE_POOL_SIZE_0
#define CYGOPT_FS_JFFS2_ERASE_PENDING_ON_MOUNT 1
#define CYGNUM_FS_JFFS2_ICACHE_SIZE 8
#define CYGNUM_FS_JFFS2_ICACHE_SIZE_8

#endif
