#ifndef CYGONCE_PKGCONF_INFRA_H
#define CYGONCE_PKGCONF_INFRA_H
/*
 * File <pkgconf/infra.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

/***** proc output start *****/
#include <pkgconf/system.h>
/*****  proc output end  *****/
#define CYGPKG_INFRA_DEBUG 1
#define CYGDBG_USE_ASSERTS 1
#define CYGDBG_INFRA_DEBUG_PRECONDITIONS 1
#define CYGDBG_INFRA_DEBUG_POSTCONDITIONS 1
#define CYGDBG_INFRA_DEBUG_LOOP_INVARIANTS 1
#define CYGDBG_INFRA_CHECK_FUNC_PTR 1
#define CYGDBG_USE_STACK_STATUS_TRACING 1
#define CYGDBG_USE_ASSERT_FOR_STACK_CHECK 1
#define CYGDBG_ASSERT_USAGE_RATE_FOR_STACK_CHECK 90
#define CYGDBG_ASSERT_USAGE_RATE_FOR_STACK_CHECK_90
#define CYGDBG_STACK_CHECK_TASK_TOTAL_NUM 64
#define CYGDBG_STACK_CHECK_TASK_TOTAL_NUM_64
#define CYGINT_INFRA_DEBUG_TRACE_IMPL 1
#define CYGINT_INFRA_DEBUG_TRACE_IMPL_1
#define CYGDBG_INFRA_DEBUG_TRACE_ASSERT_BUFFER 1
#define CYGDBG_INFRA_DEBUG_FUNCTION_PSEUDOMACRO 1
#define CYGPKG_INFRA_STARTUP 1
#define CYGPKG_INFRA_OPTIONS 1
#define CYGNUM_TESTS_RUN_COUNT 1
#define CYGNUM_TESTS_RUN_COUNT_1

#endif
